### ISSUE TITLE
Is it possible to plot 2 or 3 charts side-by-side?

### ISSUE THREAD

**Issue by ColinDe** [davidgohel/ReporteRs#102]
Saw this question just recently asked in StackOverflow (http://stackoverflow.com/questions/34302485/side-by-side-plotting-in-bsdoc-using-reporters) but I'd like to do it with ggplot as well if possible.

Simple 1 plot
myggplot = qplot(Sepal.Length, Petal.Length
                 , data = iris, color = Species
                 , size = Petal.Width )
mydoc = addPlot( doc = mydoc , fun = print, x = myggplot ).

2 plots side by side?
myggplot = qplot(Sepal.Length, Petal.Length
                , data = iris, color = Species
                , size = Petal.Width, alpha = I(0.7))

myggplot2 = qplot(Sepal.Length, Sepal.Width
                 , data = iris, color = Species
                 , size = Petal.Width, alpha = I(0.7))

layout <- grid.arrange(arrangeGrob(myggplot, myggplot2, ncol=2, nrow=1))

Is something similar possible in ReporteRs?

**Comment by davidgohel** [comment]
Yes with this kind of code:

    doc <- addPlot( doc = doc , fun = function(){
        grid.arrange(arrangeGrob(myggplot, myggplot2, ncol=2, nrow=1), newpage = F)
    } )

**Comment by davidgohel** [comment]
thx for letting me know about that SO question

**Comment by ColinDe** [comment]
Thanks for your amazing R package!!!

**Comment by davidgohel** [comment]
thanks
