### ISSUE TITLE
docx TOC : display titles of level 4 and more

### ISSUE THREAD

**Issue by ElenaDatak** [davidgohel/ReporteRs#103]
Hello David, 

I would like to know how to display titles of level 4 and more in the TOC. Using
  mydoc <- addTitle( mydoc, pot("Title 4"), underline=TRUE, level = 4)
the title doesn't appear in the table of contents. Is there any option in addTOC which I did'nt saw, or a trick to automatically increase levels of TOC in Word itself ?

Thank you for your work,
Elena

**Comment by davidgohel** [comment]
Hello Elena

Unfortunately, there is no option for that. The TOC is displaying title 1 to title 3. You can only do it manually in Word for now.

I will make an option in a future release.

David

**Comment by ElenaDatak** [comment]
Ok David, thank you for you response !

Elena

**Comment by davidgohel** [comment]
Hi Elena,

The new version will let you add more than 3 levels with parameter `level_max`.

++
David
