### ISSUE TITLE
Reporterjars hangs on install on Debian

### ISSUE THREAD

**Issue by noamross** [davidgohel/ReporteRs#104]
When I install ReporteRsjars via CRAN or GitHub,  R hangs on install at

    ** testing if installed package can be loaded

I am running R in a Docker container with the rocker/hadleyverse image.  It is running Debian Linux, has R 3.2.3 and Java 1.7.0_91, and rJava works fine.

**Comment by davidgohel** [comment]
I would need to install docker to test your case. I will try next week. 
When you are running R from the command line, do you get a message with more details?

**Comment by noamross** [comment]
I don't get more details, but I've found this happens with multiple packages with rJava dependencies, so don't think this is due to your package.  I've laid out more details in an issue of the Docker maintainer here: https://github.com/cardcorp/card-rocker/issues/1

**Comment by davidgohel** [comment]
thanks for the information

FYI, long term plan is to get rid of java in ReporteRs.
