### ISSUE TITLE
Error in UseMethod("addSlide") :

### ISSUE THREAD

**Issue by scdavis50** [davidgohel/ReporteRs#105]
Great package - it's been super helpful but now I am getting a weird error.  It runs about 2-3 slides and then I get the following messages:

Error in UseMethod("addSlide") : 
  no applicable method for 'addSlide' applied to an object of class "function"
Error in UseMethod("addTitle") : 
  no applicable method for 'addTitle' applied to an object of class "function"
Error in UseMethod("addPlot") : 
  no applicable method for 'addPlot' applied to an object of class "function"

Here's a sample of my code, it's all the same except for changed variable names:
#code to generate economic slide deck
library(quantmod)
library(ggplot2)
library(ReporteRs)
library(gdtools)
library(rvg)

deck = pptx()
getSymbols("RECPROUSM156N",src="FRED")
RECPROUSM156N.df <- data.frame(index(RECPROUSM156N),coredata(RECPROUSM156N),stringsAsFactors=FALSE)
colnames(RECPROUSM156N.df) <- c("date","percent")
RECPROUSM156N5.df <- subset(RECPROUSM156N.df, date > as.Date("2000-01-01") )
oil <- ggplot( RECPROUSM156N5.df, aes(date) ) + 
  geom_line( aes( y = percent ) ) +
  labs( title = "Smoothed U.S. Recession Probabilities")
deck = addSlide( deck, "Standard Title and Content")
deck = addTitle( deck, "Smoothed U.S. Recession Probabilities")
deck = addPlot( deck, fun = print, x = oil, vector.graphic = TRUE)

Here's my session info from the windows machine.  Getting the same result running RStudio on a digital ocean server.
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rvg_0.0.5           gdtools_0.0.6       ReporteRs_0.8.2     ReporteRsjars_0.0.2
 [5] ggplot2_1.0.1       quantmod_0.4-5      TTR_0.23-0          xts_0.9-7          
 [9] zoo_1.7-12          rJava_0.9-7        

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6  digest_0.6.8      grid_3.1.3        gtable_0.1.2      labeling_0.3     
 [6] lattice_0.20-30   magrittr_1.5      MASS_7.3-39       munsell_0.4.2     plyr_1.8.3       
[11] proto_0.3-10      R.methodsS3_1.7.0 R.oo_1.19.0       R.utils_2.1.0     Rcpp_0.12.2      
[16] reshape2_1.4.1    scales_0.3.0      stringi_1.0-1     stringr_1.0.0     tools_3.1.3      
[21] xml2_0.1.2

**Comment by davidgohel** [comment]
Hi,

Sorry, I can't reproduce it.

You're using the version 0.8.2 so you don't need rvg nor gdtools. The version on github is using them but it's not on cran yet (soon...)

The layout "Standard Title and Content" does not exists in the default template, I changed it to "Title and Content". 

Then I ran 


```
library(quantmod)
library(ggplot2)
library(ReporteRs)
# library(gdtools)
# library(rvg)

deck = pptx()
getSymbols("RECPROUSM156N", src = "FRED")
RECPROUSM156N.df <-
  data.frame(index(RECPROUSM156N),
             coredata(RECPROUSM156N),
             stringsAsFactors = FALSE)

colnames(RECPROUSM156N.df) <- c("date", "percent")
RECPROUSM156N5.df <- subset(RECPROUSM156N.df, date > as.Date("2000-01-01"))
oil <- ggplot(RECPROUSM156N5.df, aes(date)) +
  geom_line(aes(y = percent)) +
  labs(title = "Smoothed U.S. Recession Probabilities")

deck = addSlide(deck, "Title and Content")
deck = addTitle(deck, "Smoothed U.S. Recession Probabilities")
deck = addPlot(deck,
               fun = print,
               x = oil,
               vector.graphic = TRUE)
writeDoc(deck, file = "deck.pptx")
```

And everything was OK...

**Comment by scdavis50** [comment]
David-

Thanks for the quick reply.  I'll upload the package from github and try
that.

Here's the full code that's giving me problems -- I use your package for
presentations to clients, and this is the only script that gives me trouble.

Thanks again!

On Sat, Jan 23, 2016 at 4:30 AM, David Gohel <notifications@github.com>
wrote:

> Hi,
>
> Sorry, I can't reproduce it.
>
> You're using the version 0.8.2 so you don't need rvg nor gdtools. The
> version on github is using them but it's not on cran yet (soon...)
>
> The layout "Standard Title and Content" does not exists in the default
> template, I changed it to "Title and Content".
>
> Then I ran
>
> library(quantmod)
> library(ggplot2)
> library(ReporteRs)
> # library(gdtools)
> # library(rvg)
>
> deck = pptx()
> getSymbols("RECPROUSM156N", src = "FRED")
> RECPROUSM156N.df <-
>   data.frame(index(RECPROUSM156N),
>              coredata(RECPROUSM156N),
>              stringsAsFactors = FALSE)
>
> colnames(RECPROUSM156N.df) <- c("date", "percent")
> RECPROUSM156N5.df <- subset(RECPROUSM156N.df, date > as.Date("2000-01-01"))
> oil <- ggplot(RECPROUSM156N5.df, aes(date)) +
>   geom_line(aes(y = percent)) +
>   labs(title = "Smoothed U.S. Recession Probabilities")
>
> deck = addSlide(deck, "Title and Content")
> deck = addTitle(deck, "Smoothed U.S. Recession Probabilities")
> deck = addPlot(deck,
>                fun = print,
>                x = oil,
>                vector.graphic = TRUE)
> writeDoc(deck, file = "deck.pptx")
>
> And everything was OK...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidgohel/ReporteRs/issues/105#issuecomment-174169107>
> .
>



-- 
Scott Davis
3622 Durness Way
Houston, Texas 77025
832.236.5486 C
www.linkedin.com/in/scottcdavis

**Comment by davidgohel** [comment]
The 0.8.2 should work.
Did you run the code I sent with no problem?

**Comment by scdavis50** [comment]
Yes.  It seems to be one variable.

I'll try it with the new package.

Thanks!
