### ISSUE TITLE
Embed content of another document, rather than the whole document

### ISSUE THREAD

**Issue by noamross** [davidgohel/ReporteRs#106]
I was wondering if it was possible to do something like `addDocument()`, but instead of embedding the whole document in the new document, just add all of the content directly so that there isn't an embedded document.

The reason for this is that I've been generating DOCX files with RMarkdown/Pandoc (which can only create simple DOCX files, but has more extensive markdown support), then embedding them using ReporteRs into a template with watermarks, headers, etc.  The result is good but I've found that several other programs (notably LibreOffice and some other word-to-PDF/image converters), don't support the embedded document.

**Comment by davidgohel** [comment]
Hi,

This would be a nice feature but that's very complicated. 

It would require to make sure all images are copied into the target document, to copy styles with an unique id (and to modify the corresponding id of the content to embed), etc.

**Comment by davidgohel** [comment]
Sorry, should close that sooner.
