### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by Symeboy** [davidgohel/ReporteRs#107]
Hi,

This package has worked brilliantly for me so far, thanks very much!

I was wondering is there a way to specify line spacing of paragraphs? "padding.top" and "padding.bottom" within parProperties seems to only apply to the top/bottom lines only.

e.g.
addParagraph(doc, par.properties = parProperties(text.align="justify",padding.top=0.5))

Thanks,

Simon

**Comment by davidgohel** [comment]
Hi,

No but I keep the idea for the future.

If using Word, you can re-use an existing style but  it only works for Word.

**Comment by Symeboy** [comment]
Great, thanks for your help
