### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when calling addPlot

### ISSUE THREAD

**Issue by tomwenseleers** [davidgohel/ReporteRs#108]
With version 0.8.2 of ReporteRs I regularly get java.lang.ArrayIndexOutOfBoundsException errors, even when these plots were exporting with errors/problems in ReporteRs 0.7.

For example :
  
    funTest <- function(...) {
      x  <- as.matrix(mtcars)
      rc <- rainbow(nrow(x), start = 0, end = .3)
      cc <- rainbow(ncol(x), start = 0, end = .3)
      hv <- heatmap(x, col = cm.colors(256), scale = "column",
                    RowSideColors = rc, ColSideColors = cc, margins = c(5,10),
                    xlab = "specification variables", ylab =  "Car Models",
                    main = "heatmap(<Mtcars data>, ..., scale = \"column\")")
    }

    library(ReporteRs)
    pptx.file = "test.pptx"
    doc = pptx(title = "title")
    doc = addSlide( doc, slide.layout = "Title and Content" )
    doc = addPlot(doc, fun=funTest)
    # java.lang.ArrayIndexOutOfBoundsException: 2147483647Error in vector.pptx.graphic(doc = doc, fun = fun, pointsize = pointsize,  : 
    # an error occured when executing plot function.

Or a very simple example:
  
    funTest <- function(...) {
      x=1:10;y=1:10
      plot(x,y)
      legend(1,10,1:10,pch=16,lty=1)
    }
    doc = addPlot(doc, fun=funTest)

    # java.lang.ArrayIndexOutOfBoundsException: 2147483647Error in vector.pptx.graphic(doc = doc, fun = fun, pointsize = pointsize,  : 
    # an error occured when executing plot function.

Any thoughts?

cheers,
Tom

PS It's because of this error that I delayed uploading my export package to CRAN                                                                                 

    # sessionInfo()
    # R version 3.2.3 (2015-12-10)
    # Platform: x86_64-w64-mingw32/x64 (64-bit)
    # Running under: Windows >= 8 x64 (build 9200)
    # 
    # locale:
    #   [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
    # 
    # attached base packages:
    #   [1] stats     graphics  grDevices utils     datasets  methods   base     
    # 
    # other attached packages:
    #   [1] ReporteRs_0.8.2     ReporteRsjars_0.0.2 RevoUtilsMath_3.2.3

**Comment by davidgohel** [comment]
Hi, 

This is solved within the github version (see #91). I will submit to cran in few weeks.

**Comment by tomwenseleers** [comment]
Ha that's great many thanks! Will rvg then be up on CRAN for R version 3.2.3 as well?

**Comment by tomwenseleers** [comment]
Ha but with the github version I am getting another error (for both examples):
Error in rJava::.jcall(slide, "S", "getNextRelID") : 
  method getNextRelID with signature ()Ljava/lang/String; not found
Any thoughts?

sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ReporteRs_0.8.5.9000 ReporteRsjars_0.0.2  devtools_1.10.0      RevoUtilsMath_3.2.3 

loaded via a namespace (and not attached):
 [1] SSOAP_0.9-1         Rcpp_0.12.2         git2r_0.13.1        R.methodsS3_1.7.0   bitops_1.0-6        R.utils_2.2.0       tools_3.2.3         digest_0.6.9        memoise_0.2.1       lattice_0.20-33     png_0.1-7           Matrix_1.2-3        curl_0.9.5          parallel_3.2.3     
[15] SparseM_1.7         rJava_0.9-8         httr_1.0.0          stringr_1.0.0       xml2_0.1.2          gdtools_0.0.6       stats4_3.2.3        grid_3.2.3          nnet_7.3-11         data.table_1.9.6    Biobase_2.30.0      R6_2.1.1            rvg_0.0.7.9000      flexmix_2.3-13     
[29] XML_3.98-1.3        XMLSchema_0.7-2     magrittr_1.5        codetools_0.2-14    modeltools_0.2-21   BiocGenerics_0.16.1 stringi_1.0-1       RCurl_1.95-4.7      chron_2.3-47        R.oo_1.19.0

**Comment by davidgohel** [comment]
Maybe you didn't close R before reinstallation (the old jar is still attached by rJava)
Close all R sessions, install ReporteRs from github and it should be ok

**Comment by tomwenseleers** [comment]
Ha strange, I had closed R I believe. I now reinstalled with devtools::install_github('davidgohel/ReporteRsjars',force=TRUE) and that seems to have done the trick down - many thanks for that!
