### ISSUE TITLE
Error in pptx(template = '/path/to/template.pptx') : an error occured - code[LOADDOC_ERROR]

### ISSUE THREAD

**Issue by barretth** [davidgohel/ReporteRs#109]
I am having the same issue this [person](http://stackoverflow.com/questions/34185380/error-when-loading-a-template-pptx-using-reporters-package) has, but cannot find a solution online. Any idea why the package refuses to load the pptx? I have tried formatting the file as both a pptx and potx. Thanks

**Comment by davidgohel** [comment]
Can you provide `sessionInfo()`?
It looks like a duplicate of #101

**Comment by barretth** [comment]
Ah yes changing the path does it! Sorry for the duplicate post. Thanks David.

**Comment by davidgohel** [comment]
no problem
