### ISSUE TITLE
Issue with encoding/special characters in plot.

### ISSUE THREAD

**Issue by itsdalmo** [davidgohel/ReporteRs#111]
First of all, thank you for making this package David. 

#### Issue
Since upgrading to the latest version of ReporteRs (0.8.5) and rvg (0.0.7), I have noticed some issues with ReporteRs on my setup. If you look at the pictures below, and in the included PPTX files, you can see the following issues:

1. `ReporteRs` cannot show "ÆØÅ" no matter what encoding it is in. However, `rvg` can show the same plot without this issue. In addition, "ÆØÅ" can be added with for instance `addMarkdown` without issues.
2. Both `ReporteRs` and `rvg` produce plots with text-wrapping for the text boxes, which is apparent in the y-axis tick labels, as well as `geom_text` for this plot. 

**PS: This did not use to be an issue before upgrading to the latest version.**

*Vector graphic:*
![skjermbilde1](https://cloud.githubusercontent.com/assets/6603877/13426233/6d134026-dfac-11e5-96e5-e129efc0206a.PNG)

*PNG output:*
![skjermbilde2](https://cloud.githubusercontent.com/assets/6603877/13426240/7a29797e-dfac-11e5-8b60-07ee971f564b.PNG)

#### PPTX Examples
[reporters-issue.pptx](https://github.com/davidgohel/ReporteRs/files/152642/reporters-issue.pptx)
[RVG-directly.pptx](https://github.com/davidgohel/ReporteRs/files/152644/RVG-directly.pptx)

#### Code used to generate examples
```r
library(ggplot2)
doc <- ReporteRs::pptx()

add_to_pptx <- function(pptx, title = " ", p, ...) {
  doc <- ReporteRs::addSlide(doc, slide.layout = "Title and Content")
  doc <- ReporteRs::addTitle(doc, title)
  doc <- ReporteRs::addPlot(doc, fun = print, x = p, ...)
  doc
}

# 1 - Everything default
plt <- ggplot(data = mtcars, aes(x = hp, y = mpg))
plt <- plt + geom_point() + geom_text(aes(label = rownames(mtcars)))
doc <- add_to_pptx(doc, title = "Default vector graphic", p = plt)

# 2 - Special characters/latin1 encoding
df <- mtcars
rownames(df)[28] <- "Fiffig ÆØÅ"
Encoding(rownames(df)[28]) # latin1 encoding for me in this case.
plt <- ggplot(data = df, aes(x = hp, y = mpg))
plt <- plt + geom_point() + geom_text(aes(label = rownames(df)))
doc <- add_to_pptx(doc, title = "Special characters (latin-1)", p = plt)

# 3 - Special characters/UTF-8 encoding
df <- mtcars
rownames(df)[28] <- "Fiffig ÆØÅ"
rownames(df) <- stringi::stri_enc_toutf8(rownames(df))
Encoding(rownames(df)[28]) # UTF-8
plt <- ggplot(data = df, aes(x = hp, y = mpg))
plt <- plt + geom_point() + geom_text(aes(label = rownames(df)))
doc <- add_to_pptx(doc, title = "Special characters (UTF-8)", p = plt)

# 4 - Special characters/unknown encoding
df <- mtcars
rownames(df)[28] <- "Fiffig ÆØÅ"
rownames(df) <- stringi::stri_enc_tonative(rownames(df))
Encoding(rownames(df)[28]) # UNKNOWN
plt <- ggplot(data = df, aes(x = hp, y = mpg))
plt <- plt + geom_point() + geom_text(aes(label = rownames(df)))
doc <- add_to_pptx(doc, title = "Special characters (unknown)", p = plt)

# 5 - PNG output
df <- mtcars
rownames(df)[28] <- "Fiffig ÆØÅ"
Encoding(rownames(df)[28]) # latin1 encoding.
plt <- ggplot(data = df, aes(x = hp, y = mpg))
plt <- plt + geom_point() + geom_text(aes(label = rownames(df)))
doc <- add_to_pptx(doc, title = "Special characters - PNG output", p = plt, vector.graphic = FALSE)

# SAVE
ReporteRs::writeDoc(doc, file = "reporters-issue.pptx")
```

#### Session info
```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Norwegian Bokmål_Norway.1252  LC_CTYPE=Norwegian Bokmål_Norway.1252    LC_MONETARY=Norwegian Bokmål_Norway.1252
[4] LC_NUMERIC=C                             LC_TIME=Norwegian Bokmål_Norway.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gdtools_0.0.7 ggplot2_2.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3         knitr_1.12.3        xml2_0.1.2          ReporteRsjars_0.0.2 munsell_0.4.3       colorspace_1.2-6    xtable_1.8-2       
 [8] R6_2.1.2            plyr_1.8.3          tools_3.2.2         grid_3.2.2          gtable_0.2.0        rvg_0.0.7           R.oo_1.20.0        
[15] png_0.1-7           htmltools_0.3       digest_0.6.9        rJava_0.9-8         shiny_0.13.1        ReporteRs_0.8.5     R.utils_2.2.0      
[22] ggrepel_0.5.1       mime_0.4            labeling_0.3        stringi_1.0-1       scales_0.4.0        R.methodsS3_1.7.1   httpuv_1.3.3   
```

**Comment by itsdalmo** [comment]
Regarding #2:
Is it possible that you have somehow enabled text wrapping for the text-boxes? If you go to the "default vector graphic" plot in my examples above, select the entire figure, format, and uncheck textwrapping - everything looks ok again.

**Comment by davidgohel** [comment]
Hi,

Regarding issue 2, it's in rvg, I solved it monday on github (should be on cran next week).
And yes it's about text wrapping (sorry, that's something that can't be seen on mac but only with Office for Windows)

I will have a look at the first issue later this week.

David

**Comment by davidgohel** [comment]
and thanks for the reproducible example, it helps!

**Comment by itsdalmo** [comment]
Ah sorry. I did not see the commit on issue 2 before. Works again after installing from Github, thanks for clearing that up. I'm posting another issue related to `ggplot2` that appeared in the latest version of rvg I think.

**Comment by davidgohel** [comment]
Hi,

Could you try the new version (I am on a mac so I am not sure it solves everything on Windows) to see if issue is still there?

David

**Comment by itsdalmo** [comment]
Hi David,

I tried to install from Github and got the following error (for `ReporteRs` also):
```r
devtools::install_github('davidgohel/ReporteRsjars')
Downloading GitHub repo davidgohel/ReporteRsjars@master
from URL https://api.github.com/repos/davidgohel/ReporteRsjars/zipball/master
Installing ReporteRsjars
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/itsdalmo/AppData/Local/Temp/RtmpYVNOjf/devtools15e02b362e24/davidgohel-ReporteRsjars-c68f265"  \
  --library="C:/Users/itsdalmo/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'ReporteRsjars' ...
** R
** inst
** preparing package for lazy loading
** help
No man pages found in package  'ReporteRsjars' 
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/itsdalmo/Documents/R/win-library/3.2/ReporteRsjars'
* restoring previous 'C:/Users/itsdalmo/Documents/R/win-library/3.2/ReporteRsjars'
Error: Command failed (1)
```
 
But `rJava` and `ReporteRs` work just fine on their own (CRAN-versions). I'm probably doing something wrong here? Pointers appreciated :)

**Comment by davidgohel** [comment]
Hi

You don't need to reinstall `ReporteRsjars`. 

- Close R
- run `devtools::install_github("davidgohel/ReporteRs")`

**Comment by itsdalmo** [comment]
Thanks, I tried the following:
- Restarted R, ran `devtools::install_github("davidgohel/ReporteRs")` - same error. 
- Restarted again and ran `install.packages("ReporteRs")`, no issue. 
- Uninstalled `ReporteRs`, restarted and ran `devtools::install_github("davidgohel/ReporteRs")` - same error. 
- Installed again with `install.packages("ReporteRs")`. No problems again.

Suggestions?

**Comment by itsdalmo** [comment]
Googled the error.

[Problems requiring rJava in Windows](http://stackoverflow.com/questions/28367964/problems-requiring-rjava-in-windows)
```
C:\Users\itsdalmo>java -d64 -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

As far as I can see, they are both 64-bith versions - if this is what the architecture error is complaining about? Also, it works fine with the current version of `ReporteRs`?

**Comment by davidgohel** [comment]
I think that you have java 64 bits but no java 32 bits, when rJava is loaded within R32bits, it failed:

````
*** arch - i386
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error: loading failed
````

Try with this binaries:

http://win-builder.r-project.org/dzYIZcazEH03/ReporteRs_0.8.6.9000.zip

Do not forget to close your R session first.

**Comment by itsdalmo** [comment]
Works! I also notice that the `addParagraph`-bug has been fixed now also, great stuff!

And thank you for the binary.... Rstudio points to the 64-bit version of R, so I don't quite get why the error message states i386 if both Java and R are 64-bit.

**Comment by davidgohel** [comment]
cool

When you build from github, R checks installation on both config (i386 and x64).
When checking on i386, rJava cannot be loaded because (that's a guess, not 100% sure) you don't have java 32 bits installed:

- rJava within R-i386 is looking for java 32 bits (I think you don't have java 32 bits installed on your computer)
- rJava within R-x64 is looking for java 64 bits
