### ISSUE TITLE
cannot accessing variable from inline code chunk (variable scope)

### ISSUE THREAD

**Issue by PumpkinL** [davidgohel/ReporteRs#112]
If I wish to print the outcome of 9+2 in the inline code
`'r (9+2)'`
but it did not output the result the 11.

The full code is：
`doc.filename = "addMarkdown_example.docx"

options( "ReporteRs-fontsize" = 10 )
doc <- docx( )
mkd = "

You can also make `r (9+2)` to add code into other things.

"

doc = addMarkdown( doc, text = mkd, 
                   default.par.properties = parProperties(text.align = "justify", 
                                                          padding.left = 0) )

writeDoc( doc, file = doc.filename )`

**Comment by davidgohel** [comment]
Hi,

This is not implemented in ReporteRs. 

David

**Comment by PumpkinL** [comment]
Thank you. But it wored in R markdown.
