### ISSUE TITLE
Font of addPlot cannot be changed [0.8.5]

### ISSUE THREAD

**Issue by count41** [davidgohel/ReporteRs#115]
I noticed that the font family appears to be unaffected by `options('ReporteRs-default-font'='Arial')`. When adding a base plot to a pptx document using `addPlot`, the font is always Calibri. This was not an issue with ReporteRs 0.8.2. 

Code:

    require(ReporteRs)

    tfun <- function(x) { 
    barplot(x, col="red",main="Test",ylab="Test Y-Lab")
    legend("topleft",fill="red",c("Test Legend"),bty="n")
    }

    options('ReporteRs-fontsize'=8.5, 'ReporteRs-default-font'='Arial')
    ppt = pptx()
    ppt=addSlide(ppt, slide.layout="Title and Content")
    ppt=addPageNumber(ppt)
    ppt=addTitle(ppt, "Test Title")
    ppt=addFooter(ppt, "Test Footer")

    ppt=addPlot(ppt,fun=tfun,x=c(1:10))

    docname=paste(getwd(),"/Test.pptx",sep="")
    writeDoc(ppt,file=docname)

Session Info:

    R version 3.2.0 (2015-04-16)
    Platform: i386-w64-mingw32/i386 (32-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1

    locale:
    [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
    [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
    [5] LC_TIME=German_Germany.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] gdtools_0.0.7       ReporteRs_0.8.5     ReporteRsjars_0.0.2

    loaded via a namespace (and not attached):
     [1] Rcpp_0.12.3       png_0.1-7         digest_0.6.9      mime_0.4         
     [5] R.methodsS3_1.7.1 grid_3.2.0        R6_2.1.2          xtable_1.8-2     
     [9] R.oo_1.20.0       R.utils_2.2.0     xml2_0.1.2        tools_3.2.0      
    [13] shiny_0.13.1      httpuv_1.3.3      rJava_0.9-8       htmltools_0.3    
    [17] rvg_0.0.6         knitr_1.12.3

**Comment by davidgohel** [comment]
Hi,

With the new package, argument `fontname` is deprecated. 
You can use arguments `fontname_serif, fontname_sans, fontname_mono, fontname_symbol` to specify fonts (this makes graphics consistant with  `par("family")`

    require(ReporteRs)
    
    tfun <- function(x) { 
      barplot(x, col="red",main="Test",ylab="Test Y-Lab")
      legend("topleft",fill="red",c("Test Legend"),bty="n")
    }
    
    options('ReporteRs-fontsize'=8.5)
    ppt = pptx()
    ppt=addSlide(ppt, slide.layout="Title and Content")
    ppt=addPageNumber(ppt)
    ppt=addTitle(ppt, "Test Title")
    ppt=addFooter(ppt, "Test Footer")
    
    ppt=addPlot(ppt,fun=tfun,x=c(1:10), fontname_sans = "Arial")
    
    docname=paste(getwd(),"/Test.pptx",sep="")
    writeDoc(ppt,file=docname)


A new release has just been submitted to CRAN, please update when it will be available (within 2 or 3 days). It will require to update `rvg` also.

David

**Comment by count41** [comment]
Hi David,

thank you very much for the reply! The only issue that is left for me now is that a line break is created for double Digits on the axis (regardless if `las` is set to 1 or 2). Nevertheless, thanks a lot for this superb package and the great job you do maintaining it. Looking Forward to the new CRAN release!

**Comment by davidgohel** [comment]
Cool

I think the second issue has been solved with `rvg` 0.8.0. Could you update the package (it's on cran).

    install.packages("rvg")

If issue is still there, you can open a new ticket.

David
