### ISSUE TITLE
Soften the `is.color` requirement.

### ISSUE THREAD

**Issue by nutterb** [davidgohel/ReporteRs#118]
I'm working on an engine to write `pixiedust` tables into `FlexTable`s.  So far, things are working smoothly, with one exception.  For HTML output, `pixiedust` permits the user to specify colors with transparencies via `"rgba(x,y,z,alpha)"`.  When I try to pass such a color to a cell background, for example, I'm met with an error that I have not requested a valid color.  Would it be reasonable to implement an option where `is.color` could either be ignored, return a warning, or return an error?

I suspect part of the answer to that question depends on what `ReporteRs` is going to do with an invalidly specified color?  Will it ignore it, or will it return an error?

**Comment by davidgohel** [comment]
I was not aware of this package! 

I think (could you check?) you're not using the latest version of ReporteRs. Transparency is now supported in `cellProperties` (since 0.8.6).

**Comment by nutterb** [comment]
I see it now.  I did have 0.8.6, but I need to translate `rgb(x,y,z,alpha)` into `#xxyyzzaa` and it will work.  Thanks for the quick response.
