### ISSUE TITLE
Superscripts and Unicode not working in ggplot titles saved into PowerPoint

### ISSUE THREAD

**Issue by kabacoff** [davidgohel/ReporteRs#119]
I am trying to create titles for ggplot2 graphs that have a superscript trademark symbol. I find that both superscripts and the trademark symbol do not work for different reasons. I am on windows 7 using either PowerPoint 2010 or 2016. Session info is given below.

Test file:

```
library(ggplot2)
library(ReporteRs)
title0 <- "My Title"
title1 <- expression(My~Title^{2})
title2 <- expression(My~Title^{"\u2122"})

p <- ggplot(data=women, aes(x=height, y=weight)) + geom_point()
p0 <- p + labs(title = title0)
p1 <- p + labs(title = title1)
p2 <- p + labs(title = title2)

doc <- pptx()
doc <- addSlide(doc, "Title and Content")
doc <- addPlot(doc, print, x=p0)
doc <- addSlide(doc, "Title and Content")
doc <- addPlot(doc, print, x=p1)
doc <- addSlide(doc, "Title and Content")
doc <- addPlot(doc, print, x=p2)
writeDoc(doc, "test.pptx")
```

The first slide is fine. In the second slide, the letters in the word "Title" are vertically jittered. The third slide produces the following error:

```
> doc <- addPlot(doc, print, x=p2)
Error in grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  Metric information not available for this family/device
```

My session info is

```
> session_info()
Session info ---------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.4 Revised (2016-03-16 r70336)
 system   x86_64, mingw32                            
 ui       RStudio (0.99.893)                         
 language (EN)                                       
 collate  English_United States.1252                 
 tz       America/New_York                           
 date     2016-03-31                                 

Packages -------------------------------------------------------------------------
 package       * version date       source                                   
 colorspace      1.2-6   2015-03-11 CRAN (R 3.2.2)                           
 devtools      * 1.9.1   2015-09-11 CRAN (R 3.2.2)                           
 digest          0.6.9   2016-01-08 CRAN (R 3.2.3)                           
 gdtools       * 0.0.7   2016-02-16 CRAN (R 3.2.4)                           
 ggplot2       * 2.1.0   2016-03-01 CRAN (R 3.2.4)                           
 gtable          0.2.0   2016-02-26 CRAN (R 3.2.4)                           
 htmltools       0.3.5   2016-03-21 CRAN (R 3.2.4)                           
 httpuv          1.3.3   2015-08-04 CRAN (R 3.2.2)                           
 knitr           1.12.3  2016-01-22 CRAN (R 3.2.4)                           
 labeling        0.3     2014-08-23 CRAN (R 3.2.2)                           
 memoise         1.0.0   2016-01-29 CRAN (R 3.2.3)                           
 mime            0.4     2015-09-03 CRAN (R 3.2.2)                           
 mrgr          * 1.1     2016-03-31 local                                    
 munsell         0.4.3   2016-02-13 CRAN (R 3.2.4)                           
 plyr            1.8.3   2015-06-12 CRAN (R 3.2.2)                           
 png             0.1-7   2013-12-03 CRAN (R 3.2.2)                           
 R.methodsS3     1.7.1   2016-02-16 CRAN (R 3.2.3)                           
 R.oo            1.20.0  2016-02-17 CRAN (R 3.2.3)                           
 R.utils         2.2.0   2015-12-11 CRAN (R 3.2.3)                           
 R6              2.1.2   2016-01-26 CRAN (R 3.2.3)                           
 Rcpp            0.12.4  2016-03-26 CRAN (R 3.2.4)                           
 ReporteRs     * 0.8.6   2016-03-31 Github (davidgohel/ReporteRs@c37a695)    
 ReporteRsjars * 0.0.2   2016-03-31 Github (davidgohel/ReporteRsjars@c68f265)
 rJava           0.9-8   2016-01-07 CRAN (R 3.2.3)                           
 rsconnect       0.4.2.1 2016-03-30 CRAN (R 3.2.4)                           
 rvg             0.0.8   2016-03-04 CRAN (R 3.2.4)                           
 scales          0.4.0   2016-02-26 CRAN (R 3.2.4)                           
 shiny           0.13.2  2016-03-28 CRAN (R 3.2.4)                           
 xml2            0.1.2   2015-09-01 CRAN (R 3.2.2)                           
 xtable          1.8-2   2016-02-05 CRAN (R 3.2.3)                           
> system("java -version")
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

Any help would be greatly appreciated!

**Comment by kainhofer** [comment]
I'm running into the same issue, with R 3.3.1 on Linux, using openjdk version 1.8.0_91.

What's interesting is that this issue is specific to ggplot. If I use the exact same axis label with a normal plot, it is exported to the pptx without any issues. 

WORKING:
`library(ReporteRs)
doc = pptx();
doc = addSlide(doc, "Title and Content")
doc = addPlot(doc, function() plot(1:3, ylab=expression("ÖÄ")))
writeDoc(doc, file="test_working.pptx")
`

NOT WORKING:
`library(ggplot2)
library(ReporteRs)
doc <- pptx()
doc <- addSlide(doc, "Title and Content")
p <- ggplot(data=women, aes(x=height, y=weight)) + 
    scale_y_continuous(name=expression("ÖÄ"))
doc <- addPlot(doc, function() print(p))
writeDoc(doc, "test_NotWorking.pptx")
`

**Comment by davidgohel** [comment]
Solved with the new package `rvg` release. 

@kainhofer I will have a look and open a new issue for that one

**Comment by annaabrahao** [comment]
Hi,
I have a very similar problem with R 3.3.3 on windows. Plotting the graph is OK, and saving with ggsave too, but not exporting to ppt:


library(ggplot2)
library(ReporteRs)


P<-c(rep(0,times=18),rep(0.5,times=18),rep(5,times=18),rep(50,times=18))
P<-as.factor(P)
N<-rep(c(rep(10,times=6),rep(30,times=6),rep(50,times=6)), times=4)
N<-as.factor(N)
set.seed(42)
Y<-runif(n=72)*10

dat<-data.frame(P=P,N=N,Y=Y)


test<-ggplot(dat, aes(x=P, y=Y)) + geom_boxplot(position="dodge", aes(fill=N))+
  ylab(expression(paste('Measurement (µmol  ',g^{-1},' root FW)')))+
  xlab(expression(paste('P supply (mg  ',kg^{-1},' soil)')))+
  labs(fill=expression(paste('N (mg ',kg^{-1},')')))

test  

doc = pptx( )
doc <- addSlide(doc, slide.layout="Title and Content")
doc <- addPlot(doc, fun=print, x=test, width=3, height=4)
writeDoc(doc, "test.pptx" )

Error in grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  Metric information not available for this family/device

I updated rvg but I still have the same problem. Hope you can help!

Cheers,
Anna
