### ISSUE TITLE
res param

### ISSUE THREAD

**Issue by jrounds** [davidgohel/ReporteRs#122]
Hi,

A standard practice to make sure word documents are portably publishable is to make the resolution of PNG about 600 dpi (this is what I learned from google about publishing with png and it really sharpened up the visual quality of my word based reports).

I am interested in your package but I am curious is there a parameter to set res?

For example in the first example for your package you have
```
myggplot = qplot(Sepal.Length, Petal.Length, data = iris, color = Species, size = Petal.Width )
```

If I was going to export this to word with a professional looking document in mind I would do something like:
```
height = 8
width = 8
res = 600
png("test.png", height = height*res, width=width*res, res=res)
print(myggplot)
dev.off()
```

And when you printed that file in word you would notice a pretty striking difference in visual quality than if you left res to the default.

My question is there anyway to do the same in your package?

Thanks so much.

**Comment by davidgohel** [comment]
Hi,

Resolution is not a parameter of addPlot. 

But you can use `addImage` to add images (rasters) you've generated (with a 600 ppp) or you can use `vector.graphic = TRUE' with `addPlot`.

    addPlot( doc, fun = print, x = myggplot, vector.graphic = TRUE )

David
