### ISSUE TITLE
Why do I need to specify par.properties in .pptx when setting offx/offy?

### ISSUE THREAD

**Issue by DaveRGP** [davidgohel/ReporteRs#123]
Been having great success with using template files to feed .pptx files with ggplot2 objects, however, I'm confused to a specific behaviour:

When adding a paragraph, and specifying where to add it to a template slide, I'm getting an error when supplying arguments to `offx` and `offy`. 

`Error in addParagraph.pptx(doc, pot("Place holder text"), height = 7,  : 
  You have to specify par.properties when using arguments offx and offy`

I've hacked a workaround by supplying  `par.properties = parLeft()`, however this seems odd as I want the text to inherit from the template, and all I'm doing here is specifying what is already set in the template.

Is this the correct way to run this, or is there a more refined fix?

**Comment by davidgohel** [comment]
Hi,

If you're using `offx` and `offy`, there is no underlying *shape template*, so you need to provide paragraph properties (mainly for text alignment and padding). 

With a default value, you would not know that using `offx` and `offy` can not be mixed with template properties ;).

**Comment by DaveRGP** [comment]
Thanks for the info, does that mean that either:
1) My present approach is as designed
2) That I need to make an amendment to my underlying template in some form. If so, what?

Dave

**Comment by davidgohel** [comment]
I am going to create a FAQ on the help site and add an entry for your question
