### ISSUE TITLE
Zebrastyle odd/even swapped

### ISSUE THREAD

**Issue by javrucebo** [davidgohel/ReporteRs#125]
Using setZebraStyle the odd and even colors are swapped, see for example in the documentation: https://davidgohel.github.io/ReporteRs/FlexTable.html#zebra_striped_tables where first line after headers should be grey but is white.

This was probably introduced with  https://github.com/davidgohel/ReporteRs/commit/7ebc54225659ba5931fc149259c9c431f9f2d227#diff-a11eeaf4005cc447c562e2887e476bfd where it now says `color_compounds <- get_color_compounds(c(even, odd))` , but should be `c(odd, even)`

**Comment by davidgohel** [comment]
thanks
