### ISSUE TITLE
Using Greek symbols in table header

### ISSUE THREAD

**Issue by marillalamb** [davidgohel/ReporteRs#128]
Hi,

I'm trying to create a flextable and print it to a word document, and I want to have Greek symbols in my table header. A chunk of code used to create my table is here:

   dt <- dt %>%
          select(Substation = substation, 
                  Feeder = feeder, 
                  Period = prd, 
                  `Enabled Hrs` = h.On, 
                  `Disabled Hrs` = h.Off, 
                  `Δ MWh` = c.dYh, 
                  `Δ Volt` = dV.avg,
                  `Pct Δ MWh` = c.dY.pct, 
                   `Pct Δ Volt` = dV.pct, 
                   `CVR Factor` = CVR.Y)  %>%
       arrange(Substation)

```
 #Make the table
 dt <- FlexTable(data = dt)

 #Export to a word doc
 mydoc <- docx( )
 mydoc <- addParagraph(mydoc, dt_text)
 mydoc <- addFlexTable(mydoc, dt)
 writeDoc(mydoc, file = paste0(dirs$out, flnm, ".docx"))
```

This works, except that the deltas are printed in my table as I". If I change the header font.family to "Symbol" then the deltas work, but the rest of my column names are nonsense. Is there a fix to include deltas in my column names as shown here, and also have them appear correctly in the table in my word document?

Thanks so much for the help in advance!
Marilla

**Comment by Aks1** [comment]
We have similar problem. Unicode symbols with arbitrary font works in Flex table, but not working in text of the Word document.
E.g. print('\U03B3") works in R.
But when I add it in doc via addParagraph with pot(), then It collapses to <U+03B3> in text.
