### ISSUE TITLE
Issues w/ landscape

### ISSUE THREAD

**Issue by jrdnmdhl** [davidgohel/ReporteRs#132]
- It doesn't seem to be possible to get the first page to be landscape (other than perhaps a template).  The only command for using landscape appears to be addSection, and using this will necessarily create first page in portrait.
- Using addSection(landscape=T) doesn't seem to work if you only add a single section.  It only takes effect if another addSection is added afterwards.

**Comment by davidgohel** [comment]
I'll make a note in the doc
