### ISSUE TITLE
preferred install_github() usage has changed

### ISSUE THREAD

**Issue by rpruim** [davidgohel/ReporteRs#135]
```r
install_github('ReporteRsjars', 'davidgohel')
install_github('ReporteRs', 'davidgohel')
```
should now be
```r
install_github('davidgohel/ReporteRsjars')
install_github('davidgohel/ReporteRs')
```

See [https://github.com/hadley/devtools](https://github.com/hadley/devtools)

**Comment by davidgohel** [comment]
Thanks

I assume you're suggesting to change the online doc. 
I will update that next time documentation will be modified.
