### ISSUE TITLE
Custom Table Properties

### ISSUE THREAD

**Issue by jovisudiardi** [davidgohel/ReporteRs#136]
Hi, David. I have following through all your getting started guide. However I could not found a way to create my own persistent customized table, something like vanilla.table.
If I use setup a properties to be used with dataframe XXXX, something like this code: 
`MyFTable = FlexTable( data =XXXX,   
 header.cell.props = cellProperties( background.color = "#C00000" ),
  header.par.props = parProperties( text.align= "center"),
  body.text.props = textProperties( font.size = 22 )
)
MyFTable`
The table were formatted properly, but if I want to RE-USE the same table properties for a different data set, say YYYY, using codes:
`MyFTable= FlexTable(YYYY)
MyFTable`
the format for dataset YYYY is revert back to default setting.

Is there a way to define those properties only Once and then re-applied to different dataset, without hard-coded it every time for every table ?

Thanks for any pointers.

**Comment by davidgohel** [comment]
If you want to redefine default arguments of `FlexTable`, create a new function like `vanilla.table`.

**Comment by jovisudiardi** [comment]
Thank you for your input.
