### ISSUE TITLE
Could writeDoc directly write html code into R for bsdoc object?

### ISSUE THREAD

**Issue by drizztxx** [davidgohel/ReporteRs#137]
Hi David,

I need to send lots of mails with table every week. [mailR](https://github.com/rpremraj/mailR) supports sending HTML formatted mail, so I considered to create mail body via bsdoc in ReporteRs. What I have done is just like:
```
library( ReporteRs )
mydoc = bsdoc( title = 'my document' )
mydoc = addFlexTable( mydoc, vanilla.table(iris[1:10,] ) )
mydoc = addParagraph( mydoc, value = "Hello World!" )
writeDoc( mydoc, file = "test.html" )
```

Since mailR only supports raw html code, I have to read the external file again into R:
```
fileName = 'test.html'
mailbody = readChar(fileName, file.info(fileName)$size)
```

then send the mail:
```
require(mailR)  
from <- "xxx@xxx.com"
to <- "xxx@xxx.com"
send.mail(from=from,
          to = to,
          subject = "Test",
          body = mailbody,
          smtp = list(host.name = "xxxx", post = 25),
          authenticate = F,
          send = T,
          html = T)
```

My question is: if ReporteRs can directly output the raw html into R rather than an external file?

Thanks,
Drizzt

**Comment by davidgohel** [comment]
Hi,

Yes, you can use function `as.html`. 

```
as.html(mydoc)
```

It does not return the whole HTML page, it returns only the HTML corresponding to the body content of the document (which seems exactly what you need!).

David

**Comment by drizztxx** [comment]
Thanks David. It works well for me!
