### ISSUE TITLE
Apply Template to Powerpoint Within Package

### ISSUE THREAD

**Issue by nicholas-vogt** [davidgohel/ReporteRs#139]
I'm using ReporteRs in my R package to export powerpoints. I have a template I want to use as the default for all slides. My current calls look like this:

```
ppt <- pptx('Automated Powerpoint', 
            template = 'powerpoints/template.pptx')
```
This works fine in the package, but my users would always need a copy of that template in their subdirectory for the function to operate. __Is there a way to call a template from within the package structure without requiring users to have a copy of the template in their subdirectories?__

I'm thinking along the same functionality as the DESCRIPTION or LICENSE files. You can call each from the package if you need to, but they're built in and don't require the user to have a local copy.

Thanks in advance!

**Comment by davidgohel** [comment]
Hi

- You can create your own package with your template in it. See http://r-pkgs.had.co.nz/inst.html
- and use that template that will be located with function `system.file`.

David

**Comment by nicholas-vogt** [comment]
This is perfect! Thanks! Learned something new today. :+1:
