### ISSUE TITLE
question re a fairly complex page layout in word

### ISSUE THREAD

**Issue by pjrdata** [davidgohel/ReporteRs#141]
Hi, I'm new to ReporteRs and have dug through the issues and doco but not sure yet if this is possible (time to just give it a try but I'm not yet sure where to start)
I produce lots of reports that have a fairly dense layout on some pages in the exec summary, lots of words, numbers and small charts, somewhat like a dashboard layout, but on a page in a word document. Imagine a page in the doc that looks something like this example here:
http://enterprise-dashboard.com/img/excel-cio-dashboard.gif
I currently process the data using R and produce csv files that go into Excel to produce the dashboards, then feed that into Word using a link to a named range. It works but is clunky. I would rather have R produce the word doc or pdf (or html if I really have to) with all the text and charts etc.
I've tried RMarkdown and that can't do it. Stuff like Shiny is no help I think, because it's all meant for online/interactive. Is there a way to do it using tables and charts in ReporteRs?
thanks, Peter

**Comment by davidgohel** [comment]
Yes, it is possible if using bookmarks with a docx template.

**Comment by pjrdata** [comment]
ok thanks David, I'll give it a try. I don't think it will quite do what I want, eg variable number of rows, but will try it out, thanks
