### ISSUE TITLE
Flextable and word documents from Rmd files

### ISSUE THREAD

**Issue by rdatasculptor** [davidgohel/ReporteRs#142]
Dear David,

Do you think it will be possible to use the flextable function within Rmd-documents when rendering word documents instead of just HTML?

To my opinion  this would this be a major enhancement of the rmarkdown workflow when rendering word documents. 

kind regards,
Jelle

**Comment by davidgohel** [comment]
Hi, 

This is not possible from what I know (no option in pandoc nor rmarkdown to insert raw open xml into a doc). 

David
