### ISSUE TITLE
Is there a way to add a bookmark referenced content and preserve/recreate the bookmark?

### ISSUE THREAD

**Issue by JerryBlack** [davidgohel/ReporteRs#145]
Is there a way to add a bookmark referenced content and preserve/recreate the bookmark for subsequent replacement. I would like to reuse ReporteRs created output files as templates for subsequent re-processing, so that content created by ReporteRs could be edited in Word and subsequent be updated again with R content using ReporteRs. I my mind this requires preserving the Bookmark structure around added R content.

**Comment by davidgohel** [comment]
Hi 
The new version should fix that issue (bookmarks were supposed to stay after replacement). 

A vignette has been created to explain the bookmark system. 

    devtools::install_github("davidgohel/ReporteRs", build_vignettes = TRUE)

**Comment by JerryBlack** [comment]
Hi David,

Thanks for the update. Not sure if it works for me yet, as I appear to have a load/permission error of some sort on OS X Sierra


> library(rJava)
> .jinit() 
[1] 0
> #require(rJava)
> .jcall('java.lang.System','S','getProperty','java.version')
[1] "1.7.0_51"
> 
> devtools::install_github("davidgohel/ReporteRs", build_vignettes = TRUE)
Downloading GitHub repo davidgohel/ReporteRs@master
from URL https://api.github.com/repos/davidgohel/ReporteRs/zipball/master
Installing ReporteRs
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  build  \
  '/private/var/folders/n8/jr279xm13j724j13f4l_j9cc0000gn/T/RtmpmZQE1P/devtools4fc16317997/davidgohel-ReporteRs-c16e3f2'  \
  --no-resave-data --no-manual 

* checking for file ‘/private/var/folders/n8/jr279xm13j724j13f4l_j9cc0000gn/T/RtmpmZQE1P/devtools4fc16317997/davidgohel-ReporteRs-c16e3f2/DESCRIPTION’ ... OK
* preparing ‘ReporteRs’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘ReporteRs’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Error : package ‘ReporteRsjars’ could not be loaded
ERROR: lazy loading failed for package ‘ReporteRs’
* removing ‘/private/var/folders/n8/jr279xm13j724j13f4l_j9cc0000gn/T/RtmpD4fT3W/Rinst565a232c501/ReporteRs’
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)

**Comment by davidgohel** [comment]
Start from a new session and run only the following:

    devtools::install_github("davidgohel/ReporteRs", build_vignettes = TRUE)

(ReporteRs will `jinit` things for you...)

**Comment by JerryBlack** [comment]
Thanks, hmm,  I get...


R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[1] "ecomod.workdirectory is /Users/jerry"
[1] "ecomod.directory is /Users/jerry/GitHub/ecomod"
[1] ".Rprofile completed"
[Workspace loaded from ~/.RData]

> devtools::install_github("davidgohel/ReporteRs", build_vignettes = TRUE)
Downloading GitHub repo davidgohel/ReporteRs@master
from URL https://api.github.com/repos/davidgohel/ReporteRs/zipball/master
Installing ReporteRs
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  build  \
  '/private/var/folders/n8/jr279xm13j724j13f4l_j9cc0000gn/T/Rtmpp1pXoe/devtools570d79528cbc/davidgohel-ReporteRs-c16e3f2'  \
  --no-resave-data --no-manual 

* checking for file ‘/private/var/folders/n8/jr279xm13j724j13f4l_j9cc0000gn/T/Rtmpp1pXoe/devtools570d79528cbc/davidgohel-ReporteRs-c16e3f2/DESCRIPTION’ ... OK
* preparing ‘ReporteRs’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘ReporteRs’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Error : package ‘ReporteRsjars’ could not be loaded
ERROR: lazy loading failed for package ‘ReporteRs’
* removing ‘/private/var/folders/n8/jr279xm13j724j13f4l_j9cc0000gn/T/RtmpW5ajec/Rinst572f2c7852a/ReporteRs’
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
> 

and my .Rprofile which might somehow tweak things  looks like

#
# You can use this file to load packages, set options, etc.
#
# NOTE: changes in this file won't be reflected until after you quit
# and start a new session
#

# ecomod specific
ecomod.workdirectory = getwd() # file.path( "C:", "R", "workspace" )    ### replace with correct path to R workspace
print(paste("ecomod.workdirectory is",ecomod.workdirectory))
ecomod.directory = file.path( "/Users","jerry","GitHub", "ecomod" )  ### the correct path to cloned folder
#ecomod.directory = file.path("/Volumes", "MyBook4T", "Projects", "ArcticTrout" )  ### replace with modified path for our folder
print(paste("ecomod.directory is",ecomod.directory))
source( file.path( ecomod.directory, "_ecomodSetup", "ecomod.rprofile.r" ) ) ### initializes the ecomod environment

print('.Rprofile completed')


Not sure what’s wrong yet...

**Comment by davidgohel** [comment]
and this?
http://stackoverflow.com/questions/30738974/rjava-load-error-in-rstudio-r-after-upgrading-to-osx-yosemite

**Comment by JerryBlack** [comment]
Hi David,

I had done

sudo ln -s $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib /usr/local/lib
sudo R CMD javareconf

previously to get the 1st install running.

Not sure what changed, but I had to re-issue

sudo R CMD javareconf

to get your new Github version installed

devtools::install_github("davidgohel/ReporteRs", build_vignettes = TRUE)

Thanks!.


Now I still having problems wrapping my aging brain around the proper paradigm to create / recreate docx files using the package.

I can do the following:

doc <- docx(template = '/Users/jerry/Dropbox/Cod_Seal_2016/Seal\ cod\ data\ sets_Oct_27_2016_Rev3.docx')
doc <- addParagraph( doc
                     , value = "This is a 3rd Test Insertion"   
                     , stylename = "Normal"
                     , bookmark = "TRD_Reference_Document")
#doc = addRScript(doc, text = "x = rnorm(100);plot(density( x ) )")
doc = addPlot(doc, fun = function() {x = rnorm(100);
  plot(density( x ) )},vector.graphic=TRUE,width=5,height=7,
  par.properties = parProperties(text.align = "center"), bookmark = "TRD_Reference_Document2")
writeDoc( doc, '/Users/jerry/Dropbox/Cod_Seal_2016/Seal\ cod\ data\ sets_Oct_27_2016_Rev4.docx')

addParagraph...
  will successfully addParagraph and preserve the bookmark.

addPlot...
  addPlot will add the graphic into the document at the 2nd bookmark, but it wipes the bookmark.
  If I leave out the bookmark parameter, then the plot is added to the end of the document.

If I’m doing things the correct way, is it possible to have addPlot preserve it’s bookmark as well?

Similarly it would be nice (pie-in-the-sky) to be able to add an arbitrary mixture of content to a single bookmark
e.g.
  doc <- addContent(
        addParagraph( doc, value = "This is a 3rd Test Insertion"   , stylename = “Normal”),
        addPlot(doc, fun = function() {x = rnorm(100);
             plot(density( x ) )},vector.graphic=TRUE,width=5,height=7,
             par.properties = parProperties(text.align = "center"), bookmark = "TRD_Reference_Document2”),
        bookmark = "TRD_Reference_Document")
 
but then again I have no idea on how you might do that :)

Cheers

**Comment by davidgohel** [comment]
oups, forgot to fix when `vector.graphics=TRUE`. (`vector.graphics=TRUE` should work).

**Comment by davidgohel** [comment]
Hi,

The addPlot issue for preserving bookmark should be solved now.

> be able to add an arbitrary mixture of content to a single bookmark

This can be done with `pot` objects. See https://github.com/davidgohel/ReporteRs/issues/149
 
KR
David
