### ISSUE TITLE
FlexTable not fitting prepared space in PPTX

### ISSUE THREAD

**Issue by Martin119** [davidgohel/ReporteRs#146]
Hi David, thanks for one of the most useful libraries in R ever.

I am currently trying to work with the Flextable. It seems that its size may vary and be even out of the whole slide in Powerpoint. Probably understandable yet I would need to cope with this situation.

For example in the IRIS example if the table is larger it will not fit even to the whole slide

`MyFTable <- FlexTable(iris[1:50,] ) 
`
(50 instead of 10 in the original example). 

Is there any easy way to solve this situation? To fit the table to the prepared space or at least try it and get some feedback from Flextable that is or is not possible.
Thanks and Thanks for this library.

Martin.

**Comment by davidgohel** [comment]
Hi

Not for now. 
I am preparing a new API that will let you know the height of flextables and to control it. You can have a try here (sorry the help page on sizing is empty, wip):

https://github.com/davidgohel/flextable

It's not ready to be used within ReporteRs but it should be possible soon. 

David

**Comment by Martin119** [comment]
Thank you for your answer and your effort with this library.

Martin.
