### ISSUE TITLE
PPTX paragraph formatting from template lost with latest update

### ISSUE THREAD

**Issue by jaohar** [davidgohel/ReporteRs#147]
Hello, I recently updated to the latest version of ReporteRs and now my PPTX template is not applying paragraph formatting from template. Nothing else has changed. The example demo also has this problem. Please let me know if this is a bug or if you think I may be doing something wrong.

Thanks very much for all your time developing this software.

-Jonathan

**Comment by davidgohel** [comment]
Hi Jonanthan,

I will have a look later this week - this looks like a bug I have already solved (I just need to understand if I canceled the fix or if it's a new problem)

**Comment by davidgohel** [comment]
Should be fixed now. Reopen issue if not.

David
