### ISSUE TITLE
change font.size in addTitle PPTX

### ISSUE THREAD

**Issue by AntoineBrisacier** [davidgohel/ReporteRs#156]
Hello David,
I try to change font size of my title in a powerpoint slide using pot object.
But I get the following error message :
    Error in .jcall(slide, "I", "addTitle", value) :   method addTitle with signature ()I not found
    Called from: .jcall(slide, "I", "addTitle", value)_

Is there another way to proceed without changing the original template
Regards
Antoine

**Comment by davidgohel** [comment]
Hello Antoine,

Yes, there is another way, you will find below an solution using addParagraph. 

KR, 
David

```
library(ggplot2)
library(magrittr)
library(ReporteRs)
gg <- ggplot(mtcars, aes(x = mpg, y = cyl, color = disp)) + geom_point()

pptx() %>%
  addSlide("Title and Content") %>%
  addParagraph(pot("pa pa pa pam", format = textBold(font.size = 20)), 
               par.properties = parProperties(), offx = 1, offy = .5, width = 11, height = 1 ) %>%
  addPlot(fun = print, x = gg, vector.graphic = TRUE, offx = 1, offy = 1.5, width = 6, height = 5) %>%
  writeDoc("antoine.pptx")
```
