### ISSUE TITLE
Styles using template not working 

### ISSUE THREAD

**Issue by MarioGS** [davidgohel/ReporteRs#157]
Hi David,

I am testing the template feature and it is not working as I would expect:

1) I simple template in word and I saved it as my_template.docx in: 

> C:/Users/Mario/Documents/my_template.docx

I only defined the style for "Normal". Concretely, I defined the font to be green, "Agency FB" and size 18 and I added an image in the header (as it would be a logo).

Then, in R I used the following code:
 
```
library( ReporteRs )

# Creation of mydoc, a mydocx object
mydoc <- docx( template = 'C:/Users/Mario/Documents/my_template.docx', empty_template = TRUE)

# add into mydoc first 10 lines of iris
mydoc <- addFlexTable( mydoc, vanilla.table(iris[1:10,] ) )

# add a page break
mydoc <- addPageBreak( mydoc )

# add text with stylename "Normal" into mydoc 
mydoc <- addParagraph( mydoc, value = "Hello World! Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!")

# add a plot into mydoc 
mydoc <- addPlot( mydoc, function() barplot( 1:8, col = 1:8 ) )

filename <- tempfile(fileext = ".docx") # the document to produce
# write the doc 
writeDoc( mydoc, file = "test.docx")

browseURL("test.docx")

```

I was expecting the text in addParagraph() to be green. However, it is not!

I also tried: 

`mydoc <- docx( template = 'C:/Users/Mario/Documents/my_template.docx')
` 
but I had the same output. The curioous thing is that when I open the document I can see the style in green.

![image](https://cloud.githubusercontent.com/assets/9901945/20859985/17c43660-b96e-11e6-91fe-91426b1dcfb7.png)

Any suggestions?

Thanks in advance,

PS:

> sessionInfo()
> R version 3.2.3 (2015-12-10)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
> [4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rJava_0.9-8         ReporteRs_0.8.7     ReporteRsjars_0.0.2 mrgsolve_0.7.6     
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8               knitr_1.15.1              xml2_1.0.0                magrittr_1.5             
>  [5] munsell_0.4.3             colorspace_1.3-1          xtable_1.8-2              R6_2.2.0                 
>  [9] RcppArmadillo_0.7.500.0.0 plyr_1.8.4                dplyr_0.5.0               tools_3.2.3              
> [13] grid_3.2.3                gtable_0.2.0              rvg_0.1.1                 R.oo_1.21.0              
> [17] png_0.1-7                 DBI_0.5-1                 htmltools_0.3.5           lazyeval_0.2.0           
> [21] assertthat_0.1            digest_0.6.10             tibble_1.2                shiny_0.14.2             
> [25] ggplot2_2.2.0             R.utils_2.5.0             mime_0.5                  labeling_0.3             
> [29] scales_0.4.1              gdtools_0.1.3             R.methodsS3_1.7.1         httpuv_1.3.3             
> 
>

**Comment by davidgohel** [comment]
Hi,

`addParagraph` should be used with argument `stylename="Normal"`

David

**Comment by MarioGS** [comment]
Hi David,

I have also tried with 

`mydoc <- addParagraph( mydoc, stylename="Normal", value = "Hello World! Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!Hello World!")
`

but the output is the same. The color is still black instead of green :(

**Comment by davidgohel** [comment]
I made tests, and cannot reproduce the issue.
Are you really sure? If yes, send the template on google-groups. I will make a test with it later.
