### ISSUE TITLE
addParagraph - preserve bookmark

### ISSUE THREAD

**Issue by maschere** [davidgohel/ReporteRs#158]
Hello David,

thanks for your continued work on ReporteRs. Recently you added the behaviour that addPlot / addImage preserve the bookmark (this turned out to be extremely important for our workflow, as the "generated" report is edited elsewhere and then sent back to us to update all figures and tables).

Is it possible to change addParagraph in the same way (maybe with an optional parameter) such that it also allows to keep the bookmark?

**Comment by davidgohel** [comment]
Hello 

This was a bug, it should be solved in the last github version (that will be send to cran soon)

Could you check?
David

**Comment by maschere** [comment]
Ah yes, thank you! Working as expected, addParagraph keeps bookmarks in the current github version.

**Comment by davidgohel** [comment]
thanks
