### ISSUE TITLE
Vertical headers not available in html output

### ISSUE THREAD

**Issue by maschere** [davidgohel/ReporteRs#159]
Hi David,

we are using FlexTable in an interactive Shiny App. When specifiying vertical header names, the html output of renderFlexTable (or also in the Viewer pane for that matter) still shows horizontal names. The .docx output is working correctly however.

Code to reproduce:
`#shows horizontal header names in the Viewer, same bug appears in renderFlexTable
vanilla.table(head(iris), text.direction = "btlr")
#addFlexTable works correctly though`

**Comment by davidgohel** [comment]
Yes,

There is no support for that in HTML right now.
