### ISSUE TITLE
flexTable extends beyond margins on GNU/Linux

### ISSUE THREAD

**Issue by iembry-USGS** [davidgohel/ReporteRs#160]
I followed the example to create document_example.docx on a GNU/Linux system. I opened up the document in LibreOffice Writer on the GNU/Linux system and the flexTable only showed 2 columns on the page as all other columns were beyond the margins. I opened up the same file in Microsoft Word on a MS Windows system and the flexTable appeared correctly.

Can you test creating and viewing flexTables in LibreOffice and Microsoft Word on both MS Windows and GNU/Linux systems?

Also, is it possible to use LaTeX instead of html for tables?

Thank you.

**Comment by davidgohel** [comment]
Hi

There is no support for viewing MS docs in LibreOffice. LO do not handle all OOXML standard.

> Also, is it possible to use LaTeX instead of html for tables?

Unfortunately no.

**Comment by iembry-USGS** [comment]
@davidgohel   Thank you for letting me know.
