### ISSUE TITLE
ReporteRs no longer uses the properties of place holders from PPTX templates

### ISSUE THREAD

**Issue by luisd303** [davidgohel/ReporteRs#163]
My template has a title. Below the title, it has a sub-title. It's a small description of the graph. Below the sub-title, it has a graph. The graph and the title work as intended. 

The sub-title on the template is blue with a font size of 15 and Arial font. In version 0.86 this worked. On the new version, the sub-title uses Times New Roman size 11 no matter what the properties used for the placeholder.  

I can create images, if my description does not make sense.

**Comment by davidgohel** [comment]
Thanks, it make sense. 

This is fix I think with the github version (soon on cran)
