### ISSUE TITLE
Tab \t and blank lines \n

### ISSUE THREAD

**Issue by slarge** [davidgohel/ReporteRs#166]
I am unable to add tab \t and blank lines \n to a document using a bookmark. I feel like this worked in previous versions (I'm using commit 4210307). Thanks for any help or ideas.
[tester.docx](https://github.com/davidgohel/ReporteRs/files/687412/tester.docx)
[AdviceTemplate.docx](https://github.com/davidgohel/ReporteRs/files/687413/AdviceTemplate.docx)

```
rm(list = ls())
library(ReporteRs)
library(magrittr)
draftDoc <- docx(template = "~/AdviceTemplate.docx")

# styles(draftDoc)
draftDoc <- draftDoc %>%
  addParagraph(value = "TEXT text \t \t text text",
               stylename = "EcoregionHeader",
               bookmark = "Ecoregion_Header") %>%
  addParagraph(value = "Two blank lines\n\n tab\t double tab \t\t like this",
               stylename = "AdviceHeading",
               bookmark = "Advice_Heading")

writeDoc(draftDoc, file = paste0("~/tester.docx"))
sessionInfo()
```

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magrittr_1.5         tidyr_0.6.0          dplyr_0.5.0          icesSAG_1.0          icesSLD_0.0-0        ReporteRs_0.8.7.9007 ReporteRsjars_0.0.2 
> [8] docxtractr_0.2.1     rJava_0.9-8         
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8       knitr_1.15.1      xml2_1.0.0        devtools_1.12.0   xtable_1.8-2      R6_2.1.2          httr_1.2.1        tools_3.3.2      
>  [9] png_0.1-7         rvg_0.1.2         R.oo_1.20.0       DBI_0.5-1         git2r_0.15.0      withr_1.0.2       htmltools_0.3.5   lazyeval_0.2.0   
> [17] assertthat_0.1    digest_0.6.10     tibble_1.2        shiny_0.14.2      purrr_0.2.2       bitops_1.0-6      R.utils_2.5.0     RCurl_1.95-4.8   
> [25] curl_2.2          mime_0.5          memoise_1.0.0     gdtools_0.1.3     R.methodsS3_1.7.1 XML_3.98-1.5      jsonlite_1.1      httpuv_1.3.3

**Comment by davidgohel** [comment]
Soft return works only within `pot` objects. 
https://github.com/davidgohel/ReporteRs/blob/master/NEWS#L235

If you want to use only text associated to a stylename when working with addParagraph and you want more than a single paragraph, you will have to use different bookmarks.

**Comment by slarge** [comment]
Thanks, David. That certainly addresses the problem at hand. When using a bookmark to replace content, can tab spacing preserved? For example, if I define a right align tab in the template and replace the content with a \t, shouldn't this \t be right aligned? Thanks in advance for your help, you are doing great work.
(New template files, below)
[AdviceTemplate.docx](https://github.com/davidgohel/ReporteRs/files/689181/AdviceTemplate.docx)
[tester.docx](https://github.com/davidgohel/ReporteRs/files/689182/tester.docx)



```
rm(list = ls())
library(ReporteRs)
library(magrittr)
draftDoc <- docx(template = "~/AdviceTemplate.docx")

base_text_prop <- textProperties(font.family = "Calibri")

heading_text_prop <- chprop(base_text_prop,
                            font.size = 9,
                            font.style = "italic",
                            text.align = "left")

# styles(draftDoc)
draftDoc <- draftDoc %>%
  addParagraph(value = pot("TEXT text \t should be right aligned",
                           format = heading_text_prop),
               bookmark = "Ecoregion_Header") %>%
  addParagraph(value = pot("More text that \t should be right aligned",
                           format = base_text_prop),
               bookmark = "Advice_Heading")

writeDoc(draftDoc, file = paste0("~/tester.docx"))
sessionInfo()
```

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magrittr_1.5         tidyr_0.6.0          dplyr_0.5.0          icesSAG_1.0          icesSLD_0.0-0        ReporteRs_0.8.7.9007 ReporteRsjars_0.0.2 
> [8] docxtractr_0.2.1     rJava_0.9-8         
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8       knitr_1.15.1      xml2_1.0.0        devtools_1.12.0   xtable_1.8-2      R6_2.1.2          httr_1.2.1        tools_3.3.2      
>  [9] png_0.1-7         rvg_0.1.2         R.oo_1.20.0       DBI_0.5-1         git2r_0.15.0      withr_1.0.2       htmltools_0.3.5   lazyeval_0.2.0   
> [17] assertthat_0.1    digest_0.6.10     tibble_1.2        shiny_0.14.2      purrr_0.2.2       bitops_1.0-6      R.utils_2.5.0     RCurl_1.95-4.8   
> [25] curl_2.2          mime_0.5          memoise_1.0.0     gdtools_0.1.3     R.methodsS3_1.7.1 XML_3.98-1.5      jsonlite_1.1      httpuv_1.3.3

**Comment by davidgohel** [comment]
Sorry, tabulations are not implemented. 

You can't have different alignments within a paragraph. Alignments are specified in paragraph styles of your template or with `parProperties` - see http://davidgohel.github.io/ReporteRs/articles/formatting_properties.html#paragraph-formatting-properties
