### ISSUE TITLE
Text bounding boxes too small when vector.graphics=TRUE

### ISSUE THREAD

**Issue by swalk3r** [davidgohel/ReporteRs#167]
Hi -
Thanks for an excellent, useful package! I have been trying to create some plots to add to a Word document. When I create pngs, everything comes out fine. When I create vector graphics, however, the text bounding boxes for text in axes, legends, value labels, etc are a bit too small and cut off the text. I tried with a .pptx and the problem was not as bad, but you can see in the example that the bottom of the "sin" label is cut off. Is there a parameter I can change to adjust the internal margins of the text boxes? I am using a Mac (OSX 10.12.2) with with Word for Mac 15.30
Example:
```
doc <- docx()
filename <- "test.docx" 
doc <- addPlot( doc, fun = function() plot(sin, -pi, 2*pi), vector.graphic = TRUE )
writeDoc( doc, file = "test.docx")

ppt <- pptx()
ppt <- addSlide(ppt,"Title and Content")
ppt <- addPlot( ppt, fun = function() plot(sin, -pi, 2*pi), vector.graphic = TRUE )
writeDoc( ppt, file = "test.pptx")
```

Word screenshot
![word example](https://cloud.githubusercontent.com/assets/8779729/21943192/18ed6eda-d99e-11e6-8d96-7bc32d7d5067.png)

Ppt screenshot
![ppt example](https://cloud.githubusercontent.com/assets/8779729/21943191/18eacc52-d99e-11e6-8bbe-4fd0e495f5d9.png)

**Comment by davidgohel** [comment]
Hi,

OK. I will write that note into the ReporteRs documentation:
https://github.com/davidgohel/rvg/blob/master/R/dml_docx.R#L30

Vector graphics for Word can not be 100% ok because there is no *valid* textbox in Word. 

For PowerPoint, there should not be any issue. Could you explain why you say "not as bad"? The graphic looks the same between png and PPTX on my computer (and on the screenshot you provided). 

> Is there a parameter I can change to adjust the internal margins of the text boxes?
No

**Comment by swalk3r** [comment]
Thanks for the response. For the PowerPoint, the y-axis label is cut off a bit at the bottom, though all the other text looks fine. I will stick with the PNG output until Microsoft gets its act together.

**Comment by davidgohel** [comment]
I doubt MS will modify PowerPoint or Word format for us :)
