### ISSUE TITLE
prevent FlexTable cell break across pages

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/ReporteRs#170]
From http://stackoverflow.com/q/41882545/3315962

**Comment by brianstamper** [comment]
Thank you for adding this. IMO being able to apply a `stylename` to table body text could be a nice fix. Perhaps if `parProperties` and `textProperties` objects could be defined by a `stylename`? (Each taking on only the relevant parts of the style for that type of object?)

**Comment by davidgohel** [comment]
Sorry, I won't have time to implement that feature.
