### ISSUE TITLE
Question: How to make a duplicate of the pptx object?

### ISSUE THREAD

**Issue by winwindeal** [davidgohel/ReporteRs#172]
Want to make a duplicate of the pptx object that has some generated pages, before making changes to it. And afterward, it can revert back . Is there any way to make a duplicate/copy of the pptx object and use it later (the original and the copy are not linked)?

**Comment by davidgohel** [comment]
This is not possible as ReporteRs stores report object in a java object and this is lost when session is stopped.

David
