### ISSUE TITLE
Question: Does padding.top, padding.bottom not work for pptx?

### ISSUE THREAD

**Issue by RaspberryPi7** [davidgohel/ReporteRs#174]
I am new to excellent package ReporteRs. I looked through the documentary and previous issues, but didn't find any solution.

This is my problem: I want to create a pptx with tables and plots. This so far works very nicely. However when I want to adjust the height of the table rows using padding.top & padding.bottom, this only works for the docx and not for the pptx

I created a litte example, for the docx-File

`library(ReporteRs)` 
`parProp = parProperties(padding.top=6, padding.bottom=6)`
`mydoc <- docx( title = "title")`
`MyFTable = FlexTable( data = mtcars[1:10 ,], body.par.props = parProp)`
`mydoc <- addFlexTable(mydoc,MyFTable)`
`filename <- "Test.docx" `
`writeDoc( mydoc, file = filename)`

Here padding works nicely. However when I use the same code for the pptx-File

`library(ReporteRs)`
`parProp = parProperties(padding.top=6, padding.bottom=6)`
`mydoc <- pptx( title = "title")`
`mydoc <- addSlide( mydoc, slide.layout = "Title and Content" )`
`MyFTable = FlexTable( data = mtcars[1:10 ,], body.par.props = parProp)`
`mydoc <- addFlexTable(mydoc,MyFTable)`
`filename <- "Test.pptx" `
`writeDoc( mydoc, file = filename)`

The vertical space remains unchained. Using e.g. padding.left works again. I just have the problem with top and bottom.

What am I doing wrong?
I use the following versions: ReporteRs_0.8.8,  ReporteRsjars_0.0.2, R 3.2.2

Thank you for any advice in advance.

**Comment by RaspberryPi7** [comment]
In pptx it only works with cellProperties not with parProperties.

`library(ReporteRs)`
`parProp = cellProperties(padding.right=6, padding.left=6)`
`mydoc <- pptx( title = "title")`
`mydoc <- addSlide( mydoc, slide.layout = "Title and Content" )`
`MyFTable = FlexTable( data = mtcars[1:10 ,], body.cell.props = parProp)`
`mydoc <- addFlexTable(mydoc,MyFTable, height=8, width=5, offx=0, offy=0)`
`filename <- "Test.pptx" `
`writeDoc( mydoc, file = filename)`

Should it also work for parProperties? Thanks.

**Comment by davidgohel** [comment]
Sorry for the delay.

I will work on that in the next coding session.

Also, if you are new to `ReporteRs`, could you use `officer` instead? This is the *reboot* version of ReporteRs. **flextable** objects are far better and flexible than **FlexTable** (in my opinion).

David
