### ISSUE TITLE
Inserting an Object

### ISSUE THREAD

**Issue by rhaydock** [davidgohel/ReporteRs#175]
Hi,

Is it possible to have a function which can attach an object to a Word document? Within word this is the feature available in the "Insert" ribbon, "Text" section, "Object" button then the "Create from File" tab. I currently have a Shiny app which analyses data then creates a report of the results using a Word document template. However I frequently get requests to attach an Excel file containing the raw data into the Word document (simply adding it as a Flex table will look ugly due to the size of the raw data table - unless I'm missing something and there is a nice way possible of doing this).

Thanks!

**Comment by davidgohel** [comment]
Hi 

Sorry, this is not a feature. Maybe later but more likely later in new package [officer](https://CRAN.R-project.org/package=officer).

David
