### ISSUE TITLE
Error in PPTX_: Graphics API version mismatch

### ISSUE THREAD

**Issue by elisanapo** [davidgohel/ReporteRs#177]
Hello,

I am working with ReporteRs on a data safe haven environment where I have little control over the update of packages (basically I have to upload any packages that I need one by one from outside of the safe haven).

I am getting the following error (with traceback), and attached is a screenshot of my session information. I think I have all the packages that are listed as required in the ReporteRs Used documentation - any idea why I might therefore be getting this error?

Many thanks
Elisa
---
Error in PPTX_(file, bg, width, height, offx = offx, offy = offy, pointsize = pointsize, : Graphics API version mismatch

13
PPTX_(file, bg, width, height, offx = offx, offy = offy, pointsize = pointsize, fontname_serif = fontname_serif, fontname_sans = fontname_sans, fontname_mono = fontname_mono, fontname_symbol = fontname_symbol, editable = editable, id = id, raster_prefix = raster_prefix, ...
12
dml_pptx(file = filename, width = width, height = height, offx = offx, offy = offy, pointsize = pointsize, fontname_serif = fontname_serif, fontname_sans = fontname_sans, fontname_mono = fontname_mono, fontname_symbol = fontname_symbol, editable = editable, bg = bg, ...
11
vector.pptx.graphic(doc = doc, fun = fun, pointsize = pointsize, fontname_serif = fontname_serif, fontname_sans = fontname_sans, fontname_mono = fontname_mono, fontname_symbol = fontname_symbol, editable = editable, offx_, offy_, width_, height_, bg = bg, ...
10
addPlot.pptx(., x = t1_plots[[index[1]]], fun = print, vector.graphic = T)
9
addPlot(., x = t1_plots[[index[1]]], fun = print, vector.graphic = T)
8
function_list[[i]](value)
7
freduce(value, `_function_list`)
6
`_fseq`(`_lhs`)
5
eval(expr, envir, enclos)
4
eval(quote(`_fseq`(`_lhs`)), env, env)
3
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
2
dummyDoc %>% addPlot(x = t1_plots[[index[1]]], fun = print, vector.graphic = T) %>% addPlot(x = t2_plots[[index[1]]], fun = print, vector.graphic = T) %>% addParagraph(value = names(t1_plots)[index[1]])
1
dots_slide_fun(i)
![reporters error sessioninfo](https://cloud.githubusercontent.com/assets/26066502/23368094/926fe83a-fd04-11e6-87ef-1f3bcbe7647f.JPG)

**Comment by elisanapo** [comment]
UPDATE: I have fixed this by uploading a full R library that had been updated with the new version of R (3.3.2).

**Comment by davidgohel** [comment]
Hi

Sorry, too late...

For a future potential reader:

There is a dependency with RVG, when this error is read, the simplest solution is to reinstall packages `rvg` and `ReporteRs`.

David
