### ISSUE TITLE
Download .pptx from a shyni app.

### ISSUE THREAD

**Issue by hairolp** [davidgohel/ReporteRs#18]
Hi David.

I was wondering if it is possible to download a. Pptx which was created using "Reporters" from a shiny app, through the "downloadHandler" function. 

So far I have used the function "downloadHandler" to enable downloading of the "knitr" reports from the shiny app, and it would be very useful if I could enable the file download of the Pptx that I create on my PC. . 

If it is possible, as I will argue in the function "downloadHandler"?

Cheers

**Comment by tarunparmar** [comment]
Hi @davidgohel , How do I link already saved file?
I have tried something like this, but no go so far:

```
ui <- fluidPage(
  downloadLink("downloadData", "Download")
)

server <- function(input, output) {

  output$downloadData <- downloadHandler(
    filename = "your-pdf-name.pdf",
    content = function(file) {
      file.copy("www/teste.pdf", file)
    }
  )
}

shinyApp(ui, server)
```

**Comment by davidgohel** [comment]
Hi @tarunparmar 

You can read that documentation, it should answer your question: https://shiny.rstudio.com/reference/shiny/0.14/downloadHandler.html
