### ISSUE TITLE
Title is not repeated

### ISSUE THREAD

**Issue by shashi108** [davidgohel/ReporteRs#180]
when table is roll on multiple page,but title is not repeated in every page.

**Comment by davidgohel** [comment]
````
library(ReporteRs)
ft_obj <- vanilla.table(iris)
doc = docx( )
doc = addFlexTable( doc, flextable = ft_obj )
writeDoc( doc, file = "add_ft_ex.docx" )
````
<img width="1259" alt="capture d ecran 2017-03-16 a 11 13 04" src="https://cloud.githubusercontent.com/assets/4331618/23991442/afbe7112-0a39-11e7-8765-37f044c7012e.png">
