### ISSUE TITLE
Table Tiltle is not repeated 

### ISSUE THREAD

**Issue by shashi108** [davidgohel/ReporteRs#182]
When table comes in more than one page than title is not repeated in every page.
please suggest how to resolve this problem.

`par_fun<-function(x,y,z){
  Title_t2<-pot(paste("Table" ,x,"Summary of Baseline Characteristics by AIS Grades - Baseline" ,y,"days"),textBold())
  
   doc <- addTitle(doc,Title_t2,par.properties = parCenter(),Level=1)
   doc <- addTitle(doc,Sub_Title_t2 ,par.properties = parCenter(),,Level=2)
  
  doc<-addParagraph(doc,"")
  MyFTable <-vanilla.table( data = z )
  MyFTable<-setFlexTableWidths(MyFTable,widths = c(2,0.8,rep(1.2,length(colnames(z))-2)))
  MyFTable[ to = "header" ] = textBold()
  MyFTable[ to = "header" ] = parCenter()
  MyFTable[ , 1:2 ] =  parProperties( text.align = "left" )
  MyFTable[ , 3:length(colnames(z))] =  parProperties( text.align = "center" )
  
  doc <- addFlexTable( doc, MyFTable,par.properties = parProperties(text.align = "center"))
 
  doc <- addPageBreak(doc)
  
  writeDoc(doc, file = "EMSI_t2.1-2.4.docx")
}
par_fun("2.1","0-3",Table_2.1)`
![qqq](https://cloud.githubusercontent.com/assets/20730599/24041746/d2cb954e-0b34-11e7-8e34-863a64b1e4e5.JPG)

**Comment by davidgohel** [comment]
This is not a problem (I doubt you can do it by hand in Word). 
You should add that title as table header.

**Comment by shashi108** [comment]
I want to repeat table in every page,please suggest some code.


`#%%%%%%%%%%%%%%%%%%%% Export in word %%%%%%%%%%%%%  
library(ReporteRsjars)
library(ReporteRs)
# Create a word document to contain R outputs
doc <- docx(template="C:/Users/Shashi/Desktop/R-RHI-ISDN2/R-RHI-ISDN/Program/Template_table 1.docx")
options( "ReporteRs-fontsize" = 9, "ReporteRs-default-font" = "Courier")

# Add a title to the document x=table no,y=baseline day,z=table
par_fun<-function(x,y,z){
  Title_t2<-pot(paste("Table" ,x,"Summary of Missing Data"),textBold())
  
  doc <- addParagraph(doc,Title_t2,par.properties = parCenter())
  doc <- addParagraph(doc,Sub_Title_t2 ,par.properties = parCenter())
  doc<-addParagraph(doc,"")
  MyFTable <-vanilla.table( data = z )
  MyFTable<-setFlexTableWidths(MyFTable,widths = c(2,0.8,rep(1,length(colnames(z))-2)))
  MyFTable[ to = "header" ] = textBold()
  MyFTable[ to = "header" ] = parCenter()
  MyFTable[ , 1:2 ] =  parProperties( text.align = "left" )
  MyFTable[ , 3:length(colnames(z))-1] =  parProperties( text.align = "center" )
  
  doc <- addFlexTable( doc, MyFTable,par.properties = parProperties(text.align = "center"))
  # Add a page break : go to next page
  doc <- addPageBreak(doc)
  # Write the Word document to a file 
  writeDoc(doc, file = "RHI_t1.docx")
}
par_fun("1","0-3",Table1)

#%%%%%%%%%%%%%
`

**Comment by davidgohel** [comment]
No because you are really not polite (and it makes me grumpy)! All is documented and I already suggested you to add your title in table headers. 

I am consultant and I would be happy to help if you need me to do your job, PM me and we can contract.
