### ISSUE TITLE
plotmath expressions for pptx()

### ISSUE THREAD

**Issue by Lukas-1** [davidgohel/ReporteRs#184]
I saw some issues when using plotmath expressions in powerpoint files. Specifically, if an expression() is composed of multiple elements joined using "*" or "~", separate textboxes are created in PowerPoint, which leads faulty vertical alignment. It would be better if the whole expression were contained in one textbox.

For example, the following code displays buggy vertical alignment of the text:

plot(1:10)
title(expression("foo" * "-" * "oo"))

Also, using an en dash in plotmath expressions causes a bug where each element of the expression is individually centered and overlaps.

P.S. thank you for developing this great package!

**Comment by davidgohel** [comment]
Hi

Sorry, it's a known issue but I don't know exactly what is wrong. 

I'll have a *coding session* probably next month and will invest on this case.

David

**Comment by davidgohel** [comment]
Issue moved to [davidgohel/rvg #19](https://github.com/davidgohel/rvg/issues/19) via [**ZenHub**](https://www.zenhub.com/)
