### ISSUE TITLE
Vertical alignment in FlexTable cells

### ISSUE THREAD

**Issue by tammoterhark** [davidgohel/ReporteRs#189]
Even though my default settings for tables are vertical alignment = top in my template.docx document
when I define a flextable the vertical alignment is always middle/centered.

Did I do something wrong? Is there a command for making vertically aligning table cells? Did I run into a bug?

**Comment by davidgohel** [comment]
No, use `vertical.align = "middle"` with function `cellProperties`. FlexTable has two arguments `header.cell.props` and `body.cell.props` that are expecting *cellProperties* objects.

```
cellprop <- cellProperties( vertical.align = "bottom" )
MyFTable <- FlexTable( data = iris[46:55, ], 
                       body.cell.props = cellprop, 
                       header.cell.props = cellprop ) 
MyFTable

```

David

**Comment by tammoterhark** [comment]
Thanks for the swift answer. But your solution did not have the effect that I hoped for. Perhaps I am overseeing something. The two images show (first picture) what I get and (2) what I hope for.

Using this code:

```
# Some Flextable settings
cellprop <- cellProperties(vertical.align = "top")
flex_table<-FlexTable(table, header.columns=FALSE, 
                          body.cell.props = cellprop, 
                          header.cell.props = cellprop)
    setFlexTableBorders(flex_table, inner.vertical = borderNone(),
                        inner.horizontal = borderNone(),
                        outer.vertical = borderNone(),
                        outer.horizontal = borderProperties(color = "#006699", style = "solid", width = 2) , 
                        body = TRUE, 
                        header = FALSE,
                        footer = FALSE)
```


![wrong](https://cloud.githubusercontent.com/assets/6483317/25338707/73e3efd8-2900-11e7-8249-fa8144b94872.png)

![right](https://cloud.githubusercontent.com/assets/6483317/25338716/791e1d16-2900-11e7-89dd-c568bd678f80.png)

**Comment by davidgohel** [comment]
Could you provide your `sessionInfo()` please?

**Comment by tammoterhark** [comment]
```
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggplot2_2.2.1       ReporteRs_0.8.8     ReporteRsjars_0.0.2 stringr_1.2.0       xlsx_0.5.7          xlsxjars_0.6.1      limer_0.1          
 [8] rJava_0.9-8         mailR_0.4.1         lubridate_1.6.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9       plyr_1.8.4        R.methodsS3_1.7.1 R.utils_2.5.0     base64enc_0.1-3   tools_3.3.3       digest_0.6.12     jsonlite_1.3     
 [9] tibble_1.2        gtable_0.2.0      png_0.1-7         shiny_1.0.1       DBI_0.6           curl_2.4          officer_0.1.1     httr_1.2.1       
[17] dplyr_0.5.0       xml2_1.1.1        knitr_1.15.1      gdtools_0.1.3     grid_3.3.3        R6_2.2.0          rvg_0.1.3         purrr_0.2.2      
[25] magrittr_1.5      scales_0.4.1      htmltools_0.3.5   assertthat_0.1    mime_0.5          colorspace_1.3-2  xtable_1.8-2      httpuv_1.3.3     
[33] stringi_1.1.2     lazyeval_0.2.0    munsell_0.4.3     R.oo_1.21.0    
```

**Comment by davidgohel** [comment]
PowerPoint, Word and HTML output are all OK for me... For now, I have no idea why you are in this case. 
What document format is used?

**Comment by tammoterhark** [comment]
Sorry, I was not clear about that. Word 365, template attached.

[template.docx](https://github.com/davidgohel/ReporteRs/files/951825/template.docx)

**Comment by davidgohel** [comment]
Your template is ok. 

<img width="632" alt="capture d ecran 2017-04-24 a 15 33 39" src="https://cloud.githubusercontent.com/assets/4331618/25339564/6f27bdfa-2903-11e7-932a-ddc75628c084.png">

**Comment by tammoterhark** [comment]
Thank you for your investigation time. Do you have any idea where I should look for the solution?

**Comment by tammoterhark** [comment]
Guess ReporteRs itself is not the problem. Maybe it's me...

**Comment by tammoterhark** [comment]
What code did you use to get this? Maybe I should play around with that..

**Comment by davidgohel** [comment]
Maybe the viewer, are you using something else then Word usual client (a web viewer for example)?

Below the code:

```
cellprop <- cellProperties( vertical.align = "top" )
MyFTable <- FlexTable( data = data.frame(text = " ok", text2 = "blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah "), 
                       body.cell.props = cellprop, 
                       header.cell.props = cellprop ) 

doc = docx(template = "template.docx" )
doc = addFlexTable( doc, flextable = MyFTable )
writeDoc( doc, file = "add_ft_ex.docx" )

```

**Comment by tammoterhark** [comment]
Thanks, I play around with that. I'll start with leaving out the border. I'll get back when I either cannot proceed, or when I found a solution.

**Comment by davidgohel** [comment]
ok, thanks

**Comment by tammoterhark** [comment]
Problem solved. Beginners fault. Applied properties to other table...  :-(

**Comment by davidgohel** [comment]
:)
