### ISSUE TITLE
How to change header content?

### ISSUE THREAD

**Issue by eusebe** [davidgohel/ReporteRs#192]
Hi, 

I would like to replace the default header names of a FlexTable object (*after* its creation).

I tried

```R
ft <- FlexTable(head(esoph))
ft[1, , to = "header"] <- c("A", "B", "C", "D", "E")
```

But the result is not exactly what I expected;
<table style="margin-left:0px;margin-right:auto;border-collapse:collapse;"><thead><tr><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">agegp</span><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">A</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">alcgp</span><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">B</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">tobgp</span><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">C</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">ncases</span><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">D</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">ncontrols</span><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">E</span></p></td></tr></thead><tbody><tr><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">25-34</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0-39g/day</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0-9g/day</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">40</span></p></td></tr><tr><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">25-34</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0-39g/day</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">10-19</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">10</span></p></td></tr></tbody><tfoot></tfoot></table>

Is it possible to obtain the following?

<table style="margin-left:0px;margin-right:auto;border-collapse:collapse;"><thead><tr><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">A</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">B</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">C</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">D</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;font-weight:bold;color:rgba(0, 0, 0, 1);">E</span></p></td></tr></thead><tbody><tr><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">25-34</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0-39g/day</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0-9g/day</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">40</span></p></td></tr><tr><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">25-34</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0-39g/day</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">10-19</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">0</span></p></td><td style="background-color:rgba(255, 255, 255, 0);border-bottom-color:rgba(0, 0, 0, 1);border-bottom-style:solid;border-bottom-width:1px;border-top-color:rgba(0, 0, 0, 1);border-top-style:solid;border-top-width:1px;border-right-color:rgba(0, 0, 0, 1);border-right-style:solid;border-right-width:1px;border-left-color:rgba(0, 0, 0, 1);border-left-style:solid;border-left-width:1px;vertical-align:middle;padding-left:0pt;padding-right:0pt;padding-top:0pt;padding-bottom:0pt;"><p style="text-align:left;padding-top:0pt;padding-bottom:0pt;padding-right:0pt;padding-left:0pt;margin-left:0pt;margin-right:0pt;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Times New Roman;color:rgba(0, 0, 0, 1);">10</span></p></td></tr></tbody><tfoot></tfoot></table>

Best, 
David

**Comment by davidgohel** [comment]
Hi David

Yes, set no row header with `header.columns = FALSE` then use `addHeaderRow` :

```
MyFTable <- FlexTable( data = iris[46:55, ], header.columns = FALSE )
MyFTable <- addHeaderRow( MyFTable, value = c("A", "B", "C", "D", "E") )
```

David

**Comment by eusebe** [comment]
So, it means that it is impossible to remove header **after** the creation of the FlexTable object?

**Comment by davidgohel** [comment]
yes
