### ISSUE TITLE
Highcharter

### ISSUE THREAD

**Issue by theyuish** [davidgohel/ReporteRs#195]
I am trying to add the output from Highcharter into word and I understand that you can use addPlot to add vector graphics. Just wonder if anyone comes across a way to have .svg file generated by hc_exporting to be included on word documents? 

```
require("dplyr")
require("highcharter")
data("citytemp")
highchart() %>%
hc_xAxis(categories = citytemp$month) %>%
hc_add_series(name = "Tokyo", data = citytemp$tokyo) %>%
hc_add_series(name = "London", data = citytemp$london) %>%
hc_exporting(enabled = TRUE,
filename = "custom-file-name")
```

Thank you.

**Comment by davidgohel** [comment]
Sorry, that is not supported by MS Word.
