### ISSUE TITLE
Put character in Apex

### ISSUE THREAD

**Issue by AndreaQ7** [davidgohel/ReporteRs#205]
Hi, Is there a way to put in apex a letter or a number? 
I'm seeing in addParagraph option but i dont find it
thank you

**Comment by davidgohel** [comment]
HI, I have no idea what is an apec, so I guess no.

**Comment by AndreaQ7** [comment]
Sorry David maybe by english dictionary was wrond i meant to put for example a little * or a little number at the end of a word like: Example*  this * is for me the apex ... how can I put a number in that position ? is there a way with addParagraph?
thank you for the patience
