### ISSUE TITLE
Replacing content in shapes deletes everything

### ISSUE THREAD

**Issue by muranyia** [davidgohel/ReporteRs#206]
I'm trying to replace content using `cursor_reach()` and `body_add_par(... pos="on")`.
When the content is inside a shape (say, in a rectangle), the first occurrence of `body_add_par()` deletes all the content from the document (and any further `cursor_reach()` attempts will fail).

**Comment by davidgohel** [comment]
Sorry, I can't help without any reproducible example. 

Also, you are talking about `officer`. Because this is a place to post issues for ReporteRs...

**Comment by muranyia** [comment]
You're right, sorry.
