### ISSUE TITLE
[enhancement] put several plots side by side

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/ReporteRs#208]
Hi David, thanks for this great library.

I used `addPlot `with `par(mfrow = c(3, 2)) ` but my docx was overcomplicated and took ages to open (my plots are really information-heavy).

I then tried to put `vector.graphic = FALSE`, but it throws an error saying this is not implemented yet if there is more than one plot. It resolved my opening speed problem though.

Are multpile PNG plots going to be implemented in the future ?

If not, could you add an option fore addPlot not to add a rarriage return in the end, so I could add several plots side by side in my document ?

**Comment by davidgohel** [comment]
Hi,

No, you can loop over graph if necessary

No, you can use pot_img instead.
https://davidgohel.github.io/ReporteRs/articles/pot.html#pot_img
