### ISSUE TITLE
Title and Content Template Issue

### ISSUE THREAD

**Issue by imamanatee** [davidgohel/ReporteRs#209]
Hi there,

I'm really excited to use this package but it seems like it's not working for the template I have... 

When I try to add a title page I get:

"Error in .jcall(doc$obj, paste0("L", class.pptx4r.LayoutDescription, ";"),  : 
  java.lang.NullPointerException"

**Comment by imamanatee** [comment]
I did notice that this was an issue already and the conversation was closed, seems like it was resolved - I installed the package today, do I have the most updated version or is there another modification I need to install?

**Comment by davidgohel** [comment]
Hi

Not the answer to your question but as you are starting, I advise you to use package `officer` instead. 

About your question, sorry, there is no reproducible code so I can't help.

**Comment by imamanatee** [comment]
Thanks very much. Okay I will look at officer, thanks!
