### ISSUE TITLE
ReporteRs as a package dependency raises an error

### ISSUE THREAD

**Issue by md0u80c9** [davidgohel/ReporteRs#215]
Hi,

I'm trying to build a package which depends upon ReporteRs. If I include ReporteRs (>= 0.8.8) in imports in my description file, I'm getting the following error:

==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Updating ssnapreports documentation
Loading ssnapreports
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
  Dependency package ReporteRs not available.
Calls: suppressPackageStartupMessages ... <Anonymous> -> load_all -> load_imports -> mapply -> <Anonymous>
Execution halted

Exited with status 1.

Conversely the command library ('ReporteRs') works fine, so I think the install has gone fine.

**Comment by davidgohel** [comment]
Hi

I am not able to reproduce that, sorry. You should have a look at packages that already imports `ReporteRs`. 

nb: If possible, switch to package `officer`.

**Comment by md0u80c9** [comment]
No problems. I'll switch to officer and see if I fare better. I notice looking briefly at it that the rJava dependency isn't there for officer so that in itself would be a blessing!

**Comment by md0u80c9** [comment]
Hi,

It's not anywhere downloadable at the minute. The tools I'm writing analyse national stroke data for publication on www.strokeaudit.org.

We plan to release the packages we have produced onto Github but I'm awaiting permission from HQIP to use the Mozilla license for them - you're more than welcome to look at them as soon as they get back to me (from my profile you'll see the empty project ready to go!)

**Comment by davidgohel** [comment]
OK, let me know when it will be available, I will see why you have that issue (or better use officer ;))

**Comment by md0u80c9** [comment]
Yes thanks for that - I wasn't aware of officer! gdtools is a bit of a pain on the Mac in terms of install, but no rJava is a definite big bonus!

**Comment by davidgohel** [comment]
I know I know... When I will have more time, I will write a note about installing `gdtools` on mac.

**Comment by md0u80c9** [comment]
Replaced this with officer (noting also today's release removes dependence on gdtools - thanks!). Works perfectly as expected within the package.
