### ISSUE TITLE
Bookmarks are only detected in the first run of code

### ISSUE THREAD

**Issue by drcarrot** [davidgohel/ReporteRs#216]
Hello, 

Firstly thank you for building ReporteRs, it is a great package! 
I am currently using ReporteRs to create a report for my institute, and the ability to use bookmarks is very important. I am running the scripts on a server, using a template with two bookmarks on the first page. When I restart my computer (but not necessarily the Rstudio session), the bookmarks are recognized, and the report's title and date appear. If I then modify the script downstream (i.e., change the size of a plot on another page) and rerun the code, the bookmarks are not recognized. If I restart the computer (but again, stay in the same Rstudio session), the bookmarks are recognized again. 

The template (attached) has two bookmarks on the title page, and the scripts are as follows: 

```
require (ReporteRs)
#read project info
form=read.table("test_form.txt", row.names=1, sep="\t", stringsAsFactors = FALSE)
doc=docx(template="report_template_empty.docx")

#Page 1
title_pot=pot(paste(form[1,]), textProperties(color = "white", font.family = "Georgia", font.size = 20 ))
date_pot=pot(paste(form[2,]), textProperties(color = "white", font.family = "Georgia", font.size = 16 ))
doc=addParagraph(doc,title_pot, bookmark="Title", par.properties= parProperties(text.align = "center"))
doc=addParagraph(doc,date_pot, bookmark="Date", par.properties= parProperties(text.align = "center"))
```

SESSION INFO
[report_template_empty.docx](https://github.com/davidgohel/ReporteRs/files/1266300/report_template_empty.docx)

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8         
 [2] LC_NUMERIC=C                 
 [3] LC_TIME=en_US.UTF-8          
 [4] LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=en_US.UTF-8      
 [6] LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8         
 [8] LC_NAME=en_US.UTF-8          
 [9] LC_ADDRESS=en_US.UTF-8       
[10] LC_TELEPHONE=en_US.UTF-8     
[11] LC_MEASUREMENT=en_US.UTF-8   
[12] LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
 [1] dada2_1.4.0         Rcpp_0.12.12       
 [3] ReporteRs_0.8.8     ReporteRsjars_0.0.2
 [5] foreach_1.4.3       indicspecies_1.7.6 
 [7] picante_1.6-2       nlme_3.1-131       
 [9] ggdendro_0.1-20     gplots_3.0.1       
[11] dplyr_0.7.2         cowplot_0.7.0      
[13] vegan_2.4-3         lattice_0.20-35    
[15] permute_0.9-4       phyloseq_1.20.0    
[17] ape_4.1             reshape2_1.4.2     
[19] RColorBrewer_1.1-2  ggplot2_2.2.1      
[21] corrplot_0.77       psych_1.7.5        
[23] biomformat_1.4.0   

loaded via a namespace (and not attached):
 [1] bitops_1.0-6               matrixStats_0.52.2        
 [3] GenomeInfoDb_1.12.2        tools_3.4.1               
 [5] R6_2.2.2                   KernSmooth_2.23-15        
 [7] lazyeval_0.2.0             BiocGenerics_0.22.0       
 [9] mgcv_1.8-18                colorspace_1.3-2          
[11] ade4_1.7-6                 mnormt_1.5-5              
[13] compiler_3.4.1             Biobase_2.36.2            
[15] xml2_1.1.1                 DelayedArray_0.2.7        
[17] officer_0.1.5              caTools_1.17.1            
[19] scales_0.4.1               stringr_1.2.0             
[21] digest_0.6.12              Rsamtools_1.28.0          
[23] foreign_0.8-69             R.utils_2.5.0             
[25] XVector_0.16.0             base64enc_0.1-3           
[27] pkgconfig_2.0.1            htmltools_0.3.6           
[29] rvg_0.1.4                  rlang_0.1.2               
[31] shiny_1.0.4                bindr_0.1                 
[33] hwriter_1.3.2              jsonlite_1.5              
[35] BiocParallel_1.10.1        gtools_3.5.0              
[37] zip_1.0.0                  R.oo_1.21.0               
[39] RCurl_1.95-4.8             magrittr_1.5              
[41] GenomeInfoDbData_0.99.0    Matrix_1.2-10             
[43] munsell_0.4.3              S4Vectors_0.14.3          
[45] gdtools_0.1.5              R.methodsS3_1.7.1         
[47] stringi_1.1.5              MASS_7.3-47               
[49] SummarizedExperiment_1.6.3 zlibbioc_1.22.0           
[51] rhdf5_2.20.0               plyr_1.8.4                
[53] grid_3.4.1                 parallel_3.4.1            
[55] gdata_2.17.0               Biostrings_2.44.0         
[57] splines_3.4.1              multtest_2.32.0           
[59] knitr_1.17                 uuid_0.1-2                
[61] igraph_1.0.1               GenomicRanges_1.28.3      
[63] codetools_0.2-15           stats4_3.4.1              
[65] glue_1.1.1                 ShortRead_1.34.0          
[67] latticeExtra_0.6-28        data.table_1.10.4         
[69] RcppParallel_4.3.20        httpuv_1.3.5              
[71] png_0.1-7                  gtable_0.2.0              
[73] purrr_0.2.3                assertthat_0.2.0          
[75] mime_0.5                   xtable_1.8-2              
[77] survival_2.41-3            tibble_1.3.3              
[79] rJava_0.9-8                iterators_1.0.8           
[81] GenomicAlignments_1.12.1   IRanges_2.10.1            
[83] bindrcpp_0.2               cluster_2.0.6   
```

**Comment by davidgohel** [comment]
Hi,

Thanks. If possible, use package `officer` instead. 

I tried to reproduce but could not. 

```
require (ReporteRs)

doc=docx(template="report_template_empty.docx")

#Page 1
title_pot=pot("coco", textProperties(color = "white", font.family = "Georgia", font.size = 20 ))
date_pot=pot("icic", textProperties(color = "white", font.family = "Georgia", font.size = 16 ))
doc=addParagraph(doc,title_pot, bookmark="Title", par.properties= parProperties(text.align = "center"))
doc=addParagraph(doc,date_pot, bookmark="Date", par.properties= parProperties(text.align = "center"))

list_bookmarks(doc)
# [1] "Title" "Date"

# If I then modify the script downstream (i.e., change the size 
# of a plot on another page) and rerun the code
doc=addPlot(doc,fun = function() barplot( 1:6, col = 2:7))

list_bookmarks(doc)
# [1] "Title" "Date"

```

**Comment by drcarrot** [comment]
Thank you! Perhaps it is related to the fact that I am using Rstudio?
I will try using *officer *instead!

Steph

**Comment by davidgohel** [comment]
No, I don't think it has anything to do with RStudio. 

If possible, can you correct the script so that I am sure to be able to reproduce your case?

Thanks
David

**Comment by drcarrot** [comment]
Hi David,

I am not sure which portion of the script needs correction, however after
running the full script a few times, I realized that running the lines I
sent you does not result in the loss of the bookmarks, so I am pasting the
code for the full report below.
If I run the lines I sent you repeatedly, there is no problem. However as
soon as I run the full script (as below), the first time I do the report
comes out without a glitch, however if I rerun the exact same script,
neither of the bookmarks are found:
[image: Inline image 1]

and

> list_bookmarks(doc)character(0)


Even if I rerun only the first few lines of code, which were working
previously. This problem is gone if I restart the computer, so I thought it
might be a problem in the tmp folder somewhere? Every time I rerun the code
the .docx file is closed though, so it might be an issue in the tmp folder
of the R session? I am not sure.

Please let me know which part you would need me to correct!

Thank you

Steph



##THE SCRIPT



form=read.table("test_form.txt", row.names=1, sep="\t", stringsAsFactors =
FALSE)
doc=docx(template="report_template_empty.docx")

#Page 1
title_pot=pot(paste(form[1,]), textProperties(color = "white", font.family
= "Georgia", font.size = 20 ))
date_pot=pot(paste(form[2,]), textProperties(color = "white", font.family =
"Georgia", font.size = 16 ))
doc=addParagraph(doc,title_pot, bookmark="Title", par.properties=
parProperties(text.align = "center"))
doc=addParagraph(doc,date_pot, bookmark="Date", par.properties=
parProperties(text.align = "center"))

doc = addPageBreak(doc)


#Page 2
doc = addTitle(doc, "Project Report",level = 1)
doc=addTitle(doc, "Customer Contact", level=2)
doc = addParagraph(doc, value= c(paste("Contact ID:",form[3,]),
paste("Project contact email:", form[4,])), par.properties =
 parProperties(list.style = 'unordered'))

doc=addTitle(doc, "Project Information", level=2)
doc = addParagraph(doc, value= c(paste("Project title:",form[1,]),
paste("Project reference:", form[5,]), paste("Service Type:", form[6,]),
paste("Project quotation:", form[7,]),paste("Running date:",
form[8,]),paste("Delivery date:", form[2,]),paste("Document status:",
form[9,])), par.properties =  parProperties(list.style = 'unordered'))
doc = addPageBreak(doc)


#Page 3
doc=addTitle(doc, "Table of Contents", level = 1)
doc=addTOC(doc)
doc=addPageBreak(doc)

#Page 4
doc=addTitle(doc, "Sequence Processing", level=1)
doc=addTitle(doc, "Read quality", level=2)
doc=addPlot(doc, fun=print, x=Qualityprof, width=6.3, height = 4)
doc=addParagraph(doc, value = paste("Figure 1. Quality plot for the forward
(A) and reverse (B) reads of sample",sample.names[1],". The distribution of
quality scores at each position is shown as a grey-scale heat map, with
dark colors corresponding to higher frequency. The plotted lines show
positional summary statistics: green is the mean, orange is the median, and
the dashed orange lines are the 25th and 75th quantiles. Read quality is
used to determine sequence trimming parameters"), stylename = "Figuurstijl")

doc=addTitle(doc, "Reads lost during processing", level=2)
read.summary.table=setZebraStyle(vanilla.table(track.trim, add.rownames =
TRUE), odd="grey", even="white")
read.summary.table= setRowsColors( read.summary.table, i=11, colors =
'#69BE28' )
doc=addFlexTable(doc, read.summary.table,
par.properties=parProperties(padding.bottom=3, text.align="center"))
doc=addParagraph(doc, value = " ")
doc=addParagraph(doc, value = "Table 1. Reads lost during each step of
processing for the first ten samples. The green row indicates the averae
values for all samples", stylename = "Figuurstijl")

doc=addTitle(doc, "Read distribution per OTU and per sample", level=2)
doc=addPlot(doc, fun=print, x=readinfo, width=6.3, height = 4)
doc=addParagraph(doc, value = "Figure 2. Reads per OTU (A) are an initial
indicator of dominance patterns within the community. Most microbial
communities exhibit a long-tailed distribution. Reads per sample(B)
indicate the quality of sequencing for each sample. During rarefaction,
samples are normalized to the same number of reads", stylename =
"Figuurstijl")

doc=addTitle(doc, "Final dataset", level=2)
doc = addParagraph(doc,
  value= c(
    paste("The dataset was rarefied to ",depth, "reads per sample"),
    paste("The final dataset contained", sum(taxa_sums(rarefied)), "reads
in total"),
    paste("The reads were assigned to", ntaxa(rarefied), "OTUs"),
    paste("Good's coverage estimator for this dataset is", round(Goods,
digits = 3)),
    paste("Samples lost during rarefaction are", lost_samples),
    paste("The seed number used for rarefaction is", seed)),
    par.properties =  parProperties(list.style = 'unordered'))

doc=addPageBreak(doc)

#Page 5
doc=addTitle(doc, "Statistical Analysis of All Samples", level=1)

doc=addTitle(doc, paste("Relative abundance of", displayx, "most abundant
phyla"), level=2)
doc=addPlot(doc, fun=print, x=ungrouped_phylum, width=6.3, height = 3.7,
pointsize=8)
doc=addParagraph(doc, value = "Figure 3. The relative abundance of the ten
most dominant phyla is a general overview of community composition in
samples", stylename = "Figuurstijl")

doc=addTitle(doc, paste("Relative abundance of", displayx, "most abundant
genera"), level=2)
doc=addPlot(doc, fun=print, x=ungrouped_genus, width=6.3, height = 3.7,
pointsize=8)
doc=addParagraph(doc, value = "Figure 4. The relative abundance of the ten
most dominant genera provides a more specific view of the patterns of
individual genera which may be of interest. Only a fraction of the
community is represented by this plot", stylename = "Figuurstijl")
doc=addPageBreak(doc)

doc=addTitle(doc, "Alpha Diversity", level=1)
doc=addPlot(doc, fun=print, x=Richness, width=6.3, height = 5, pointsize=8)
doc=addParagraph(doc, value = "Figure 5. Alpha diversity is a measurement
of the species richness in the samples. Observed OTUs are the total number
of OTUs per sample, whereas Shannon's richness accounts for both the
presence of each OTU as well as its evenness (i.e., how dominant it is
relative to other community members)", stylename = "Figuurstijl")

doc=addPageBreak(doc)


#Page 6
doc=addTitle(doc, "Statistical Analysis Including Experimental Variables:
Phylum level", level=1)
doc=addTitle(doc, paste("Relative abundance of", displayx, "most abundant
phyla, grouped by", var1), level=2)
doc=addPlot(doc, fun=print, x=phylum_by_var1, width=6.3, height =3,
pointsize=8)
doc=addParagraph(doc,  value = "Figure 6. Average relative abundance of the
ten most dominant phyla, grouped by your variable of choice indicates
whether the treatment or variable of choice affected the microbial
community at a coarse (Phylum) level. The statistical significance of these
differences is assessed in the following figure", stylename = "Figuurstijl")

doc=addTitle(doc, paste("Significant differences of top", displayx, "most
abundant phyla between", var1), level=2)
doc=addPlot(doc, fun=print, x=phylum_by_var1_sigtax, width=6.3, height =3,
pointsize=8)
doc=addParagraph(doc, value = "Figure 7. Statistical significance of
differences between treatments for the ten most abundant phyla. If the
variable of choice has two levels, differences were assessed using a t-test
for each phylum independently. If the variable has more than two levels,
the differences were assessed using a one-way ANOVA for each phylum. ",
stylename = "Figuurstijl")
doc=addPageBreak(doc)

doc=addTitle(doc, "Statistical Analysis Including Experimental Variables:
Genus level", level=1)
doc=addTitle(doc, paste("Relative abundance of", displayx, "most abundant
genera, grouped by", var1), level=2)
doc=addPlot(doc, fun=print, x=genus_by_var1, width=6.3, height =3,
pointsize=8)
doc=addParagraph(doc,  value = "Figure 8. Average relative abundance of the
ten most dominant genera, grouped by your variable of choice indicates
whether the treatment or variable of choice affected the microbial
community at a coarse (Genus) level. The statistical significance of these
differences is assessed in the following figure", stylename = "Figuurstijl")

doc=addTitle(doc, paste("Significant differences of top", displayx, "most
abundant genera between", var1), level=2)
doc=addPlot(doc, fun=print, x=genus_by_var1_sigtax, width=6.3, height =3,
pointsize=8)
doc=addParagraph(doc, value = "Figure 9. Statistical significance of
differences between treatments for the ten most abundant genera. If the
variable of choice has two levels, differences were assessed using a t-test
for each genus independently. If the variable has more than two levels, the
differences were assessed using a one-way ANOVA for each genus. ",
stylename = "Figuurstijl")
doc=addPageBreak(doc)

#Page 7
doc=addTitle(doc, "Statistical Analysis Including Experimental Variables:
Beta Diversity", level=1)
doc=addTitle(doc, paste("Principle Coordinates Analysis of all samples,
colored by", var1), level=2)
doc=addPlot(doc, fun=print, x=rarefied_ord_plot_PCoA, width=6.3, height =
5, pointsize=8)
doc=addParagraph(doc, value = paste("Figure 10. Principle Coordinates
Analysis (PCoA). This ordination shows the distribution of each sample
according to the whole community, in reduced multidimensional space.
Samples which appear closer to each other have a more similar community
composition. The axis labels indicate what percentage of the dataset's
variance is represented by each axis. This ordination is based on
the",distm, "distance metric"), stylename = "Figuurstijl")

doc=addTitle(doc, paste("PERMANOVA analyzing the significance of", var1,
"in modulating bacterial community composition"), level=2)
doc=addFlexTable(doc,vanilla.table(adonis.results),
par.properties=parProperties( text.align="center",padding.bottom=5))
doc=addParagraph(doc, value = " ")
doc=addParagraph(doc, value = "Table 2. Permutational analysis of variance.
This analysis evaluates whether the communities are significantly different
according to the different treatments", stylename = "Figuurstijl")

doc=addPageBreak(doc)
doc=addTitle(doc, "Appendix", level=1)


writeDoc(doc, file = "test.docx")

**Comment by davidgohel** [comment]
Sorry, I can't help with that. This is far to be a minimal reproducible script ;)
