### ISSUE TITLE
Error from addPlot() since update of gdtools

### ISSUE THREAD

**Issue by chrisfacer** [davidgohel/ReporteRs#217]
Hello,

I am getting an error when using the addPlot() function:

Error in PPTX_(file, bg, width, height, offx = offx, offy = offy, pointsize = pointsize,  : 

  function 'gdtools_RcppExport_validate' not provided by package 'gdtools'

It seems to be related to the recent changes in gdtools. If I install the previous version of gdtools then I don't encounter the same problem. The example that I am running is attached. The error occurs in line 51. I believe the call is OK.

Thanks,
Chris
[ReporteRs addPlot problem.txt](https://github.com/davidgohel/ReporteRs/files/1275841/ReporteRs.addPlot.problem.txt)

**Comment by davidgohel** [comment]
Hello,

There has been an update with Rcpp that had side effects with gdtools/rvg, that made a temporary break on cran (you just had it). You need to update package rvg from CRAN or github.

**Comment by chrisfacer** [comment]
Thanks David.
