### ISSUE TITLE
libpng conflict

### ISSUE THREAD

**Issue by kuzmenkov111** [davidgohel/ReporteRs#218]
Hi everyone!
I have some problems in shiny report generator when use addPlot(...) function. 
libpng warning: Application was compiled with png.h from libpng-1.6.23
libpng warning: Application  is  running with png.c from libpng-1.2.50
libpng error: Incompatible libpng version in application and library
Warning: Error in .jcall: org.docx4j.openpackaging.exceptions.Docx4JException: Error checking image format

I tried to install libpng16-6, but ubuntu 14/04 always use libpng12((

**Comment by davidgohel** [comment]
Hum, found that on google, looks very similar.

https://stackoverflow.com/questions/41989825/libpng-error-incompatible-libpng-version-in-application-and-library-in-rstudio/42025889#42025889
