### ISSUE TITLE
Java 10 compatibility

### ISSUE THREAD

**Issue by MatthiasHinz** [davidgohel/ReporteRs#225]
Did you test the package with the latest Java Runtime (10.0.1)? When I tconfigured R to use java 10 and tired to create / write a docx, it caused me the following error in R:

java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

I figured out that the corresponding libraries are seemingly not included in Java SE starting from 0. Therefore it would have to be linked to the dependencies.

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/46455026

**Comment by davidgohel** [comment]
Yes, I know. I wrote a note on the README page : 

> ReporteRs has been rewritten. The new package is [`officer`](https://cran.r-project.org/package=officer). FlexTable objects are now implemented in package [`flextable`](https://CRAN.R-project.org/package=flextable). Vector graphics are now implemented in package [`rvg`](https://CRAN.R-project.org/package=rvg) and Native Microsoft charts can be produced with package [`mschart`](https://github.com/ardata-fr/mschart). 

> Please **use officer instead of ReporteRs**. There are issues when using java > 1.8 that won’t be fixed.

Also I added another note at the top of the github page of ReporteRs saying: 

> ReporteRs will be removed from CRAN the 16th of July. please migrate to officer

Also I've deprecated `pptx()` and `docx()` in the github version. 

At this stage, I must say I don't know what else could be done to warn people... Any suggestions??

KR
David

**Comment by MatthiasHinz** [comment]
Well... no suggestions. I think it should be obvious to those who re-read the documentation. Thank you!

**Comment by MatthiasHinz** [comment]
But if it's really a problem that people frequently overlook this matter, you could still change the formatting in the documentation note to red bold text, add a red frame, or include an attention image like this: https://pixabay.com/en/important-attention-1702878/
