### ISSUE TITLE
‘ReporteRs’ is not available (for R version 3.5.1)

### ISSUE THREAD

**Issue by tcagkansokmen** [davidgohel/ReporteRs#227]
Hello I'm getting error like:
Warning in install.packages :
package ‘ReporteRs’ is not available (for R version 3.5.1)
Error in library(ReporteRs) : there is no package called ‘ReporteRs’

with trying to install;

install.packages('ReporteRs')

how can I resolve this?

**Comment by davidgohel** [comment]
Hello,

You can not solve that as it has been removed from CRAN (you can find details on the github page https://github.com/davidgohel/ReporteRs).

KR

**Comment by DanChaltiel** [comment]
Hi David, 

Unfortunately I have the same problem when I try to install it from Github: 

```
>   devtools::install_github('davidgohel/ReporteRs')
Downloading GitHub repo davidgohel/ReporteRs@master
Skipping 1 packages not available: ReporteRsjars
Installing 9 packages: httpuv, later, png, promises, ReporteRsjars, rJava, rvg, shiny, sourcetools
Error: (converted from warning) package ‘ReporteRsjars’ is not available (for R version 3.5.1)
```

I am migrating to `officer` but in the meantime I'd need my old scripts to be usable. How should I install `ReporteRs `?

**Comment by davidgohel** [comment]
Hi Dan,

It seems you did not follow installation instructions (see my previous answer)!

**Comment by DanChaltiel** [comment]
Oops, you are right, I forgot to install the `ReporteRsjars` package on this instance. 

Unfortunately, this simply brings me back to another error I've seen before:

```
> devtools::install_github('davidgohel/ReporteRs')
Downloading GitHub repo davidgohel/ReporteRs@master
Installing 7 packages: httpuv, later, png, promises, rvg, shiny, sourcetools
Error: (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'
```
Indeed, if you follow the URL, there is no `3.5` directory, only a `3.4`.

**Comment by davidgohel** [comment]
The only advice I can give there is to make sure you installed all packages named in `Imports` and you have a JRE < 9 and it should be ok

**Comment by DanChaltiel** [comment]
This was one great advice, it works like a charm. Thanks a lot !
