### ISSUE TITLE
Multiple Nested Bullet Points?

### ISSUE THREAD

**Issue by cdeterman** [davidgohel/ReporteRs#29]
@davidgohel Sorry for second question but I think your package is very good and I would really like to implement it with my work.  When you have another moment, is there a way to have multiple levels of bullet points?  Using your example, this adds bullet points for each pot object but is there a way to have pot2 nested under pot1 (i.e. indented bullet point beneath)?  I was initially thinking something with `parProperties` but I can't seem to indent the bullet points.  Thanks for your help.

```
options('ReporteRs-fontsize'=12, 'ReporteRs-default-font'='Arial')

pot1 = pot("My tailor", textProperties(color="red") ) + " is " + pot("rich"
   , textProperties(font.weight="bold") )

pot2 = pot("Cats", textProperties(color="red") ) + " and " + pot("Dogs"
    , textProperties(color="blue") )

my.pars = set_of_paragraphs( pot1, pot2 )

#Create doc
doc = docx( )
# add text with stylename BulletList - use set_of_paragraphs
doc = addParagraph( doc, value = my.pars, stylename="BulletList" )
doc = addPageBreak( doc )
```

**Comment by hafen** [comment]
+1 for this feature. I think the easiest API would be just for the input lines to be like a markdown bulleted list, i.e. lines starting with "-", "+", or "*". For every two spaces preceding these symbols, the indentation level increases by 1. You could still use `pot()` with each individual line, but still check the beginning of the line to ascertain the indentation level.

So I would envision an example like this working in this situation:

```
doc <- addParagraph(doc,
  value = c(
    "- item 1",
    "  + subitem a",
    "    * subsubitem i",
    "  + " + pot("subitem b", textProperties(font.weight = "bold")),
    "- item 2",
  ),
  parProperties(list.style = "unordered")
)
```

**Comment by davidgohel** [comment]
I like the idea! 

But I'd like it to be implemented in package `officer`. It would then be easy to get it in `ReporteRs`. 

If you can, I suggest you to migrate to `officer`, the *javaless reboot* version.
