### ISSUE TITLE
"Title and Content" Layout Bug?

### ISSUE THREAD

**Issue by cdeterman** [davidgohel/ReporteRs#30]
I'm not sure if I have done something silly or this is a bug.  I create a very simple .pptx file with a normal 'Title Only' slide and 'Title and Content' slide.  I open said file with `pptx` and try to add a new slide of the layout "Title and Content", which is returned with `slide.layouts(doc)`, but I am unable to add any text beyond a title.  I get the following error for `slide.layouts(doc, "Title and Content")` and `doc = addParagraph(doc, value=pot("test test test"), stylename="BulletList")`.  Does creating such a basic powerpoint and adding a "Title and Content" work for others?

```
doc <- pptx(template = "mydir/test.pptx")
doc <- addSlide(doc, "Title and Content")

> slide.layouts(doc, "Title and Content")
Error in text.default(coords_text_content[[i]]$x, coords_text_content[[i]]$y,  : 
  no coordinates were supplied

> doc = addParagraph(doc, value= pot("test test test"), stylename="BulletList")
Error in .jcall(slide, "I", "add", parset) : 
  java.lang.NullPointerException: No Xfrm defined
```

**Comment by retaliatoreh** [comment]
Hi David,

I'm having the same problem and the new version does not seem to fix it.  

 doc = addParagraph(doc, "Hello Word" )
Error in .jcall(slide, "I", "add", parset, as.logical(restart.numbering)) : 
  java.lang.NullPointerException: No Xfrm defined

I am guessing it has something to do with the fact that I modified the default template in a mac but I don't know how else to do this as I only own a mac.  I can't seem to attach the template, github is only accepting png, gif, jpg, how do folks usually send you that?

Thanks in advance for your help.  This package is saving my life!

Talia

**Comment by davidgohel** [comment]
Hello Talia

To send me the template, you can use the mail address written in the maintainer field in the package description

David
