### ISSUE TITLE
PowerPoint axes construction.

### ISSUE THREAD

**Issue by ehrlinger** [davidgohel/ReporteRs#32]
I'm having a problem with adding a ggplot2 graphic into a powerpoint template. I've attempted this with multiple templates, and get the same result. 

Here is a figure constructed in ggplot2:
![raw-ggplot2-figure](https://cloud.githubusercontent.com/assets/1110676/4391584/8b929fc6-4406-11e4-9044-c46013ac17b5.png)

I have modified the background for this image. By default we use transparent, but then axis labels disappear, since they are also white.

![ppt imported](https://cloud.githubusercontent.com/assets/1110676/4391603/aae00954-4406-11e4-820f-b16a3f24d121.png)
Here is the result when saving into a ppt template with ReporteRs. Notice the x axis labels and ticks are scrunched up into the panel border.

This is the code I am using to add the ggplot2 figure, saved as ccf_pptPlot.

doc = addPlot( doc=doc, fun=print, 
+                x=ccf_pptPlot+theme_ppt() ,
+                editable = TRUE,
+                offx=.75, offy=1.1, width=8, height=6)

Do the offx and offy arguments move only the graphics panel and not the axis labels? We have corrected this manually in powerpoint by selecting all labels, and moving them down enough to look reasonable.

Thanks.

**Comment by davidgohel** [comment]
Dear John,

I did not forget about the bug... It was not an easy one. 

The newer version should solve the issue. 

kind regards,
David
