### ISSUE TITLE
can not read dpi, assuming 96 dpi.

### ISSUE THREAD

**Issue by eusebe** [davidgohel/ReporteRs#34]
Hi, 

The function addImage returns systematicaly this (warning?) message:

```
> doc <- docx()
> doc <- addImage(doc, "linktomyfile.png")
can not read dpi, assuming 96 dpi.
```

The function is perfectly working, but this message seems undocumented, and I was wondering if this behaviour was normal.

Many thanks for all your work.
Best, 
David

**Comment by nicoleprause** [comment]
addImage also is not using width or height parameters. I added vector.image=T per the issue <a href="https://github.com/davidgohel/ReporteRs/issues/47">with Word</a>. The addImage.pptx is not recognized. Mac OS.

**Comment by davidgohel** [comment]
Thanks, the issue is that width or height parameters are used only if offx and offy is provided. 

    doc <- addSlide(doc, "Title and Content")
    doc <- addImage(doc, "any.png", width = 500/72, height = 400/72, offx = 1, offy = 1)

`vector.image` is a parameter of `addPlot` (not `addImage`).

**Comment by davidgohel** [comment]
#100

**Comment by nicoleprause** [comment]
That did it. Thanks!
