### ISSUE TITLE
Problem with plots when using Mac but not when  using Windows

### ISSUE THREAD

**Issue by MarioGS** [davidgohel/ReporteRs#47]
Hi David!

I have just run the example(docx) on my Macbook Pro running OSX Mavericks and I realized that there is an issue with the plot (the size is much bigger than it should be). 

![screen shot 2014-11-25 at 1 42 01 am](https://cloud.githubusercontent.com/assets/9901945/5178960/55e5fa80-7444-11e4-99a3-5232f77da17e.png)

Nevertheless, the same example works perfect on Windows 8.

I have tried with another examples and I have the same problem with the plots only when I run OSX, under Windows 8 all the examples that I tested worked perfectly.

Is there any explanation for this?

PS: All the other parts of the word document seems to be fine (I attach some screen shoots).

![screen shot 2014-11-25 at 1 51 17 am](https://cloud.githubusercontent.com/assets/9901945/5179077/ca3fe9bc-7445-11e4-8246-fc18079eb7c7.png)
![screen shot 2014-11-25 at 1 51 28 am](https://cloud.githubusercontent.com/assets/9901945/5179078/ccba3f6c-7445-11e4-80cb-ca6f175f91d3.png)
![screen shot 2014-11-25 at 1 51 33 am](https://cloud.githubusercontent.com/assets/9901945/5179081/d163e7ac-7445-11e4-8ef8-dfa81dea7a37.png)
![screen shot 2014-11-25 at 1 51 38 am](https://cloud.githubusercontent.com/assets/9901945/5179082/d3848640-7445-11e4-897e-9dbce0a6af33.png)

Thanks in advance,

Best regards

Mario

**Comment by davidgohel** [comment]
Hello,

This issue should be solved in the new version.

David
