### ISSUE TITLE
Doubled entry in a table footer row

### ISSUE THREAD

**Issue by alliquot** [davidgohel/ReporteRs#58]
What I want is to have some lines of text in a table footer.

So I wrote the code:
table <- addFooterRow( table, value="aaa", colspan = ncol(dataSet))
table[, , to="footer", newpar = TRUE] = "bbb"
table[, , to="footer", newpar = TRUE] = "ccc"

But this results in:
aaa
bbb
bbb
ccc
ccc

where I expect:
aaa
bbb
ccc

How can I add some lines to the same footer row?

EDIT:
When I changed some the code into:
table <- addFooterRow( table, value="aaa", colspan = ncol(dataSet))
     table[, , to="footer", newpar = FALSE] = "bbb"
     table[, , to="footer", newpar = FALSE] = "ccc"

the result is now: aaabbbbbbcccccc  
(3xa, 2x3xb, 2x3xc)

So the problem with doubling content is common.

This is the most actual version, compiled from sources.

**Comment by davidgohel** [comment]
Just reopened the issue so I won't forget it until it is solved...
