### ISSUE TITLE
[Question] How to add "Shift+Enter" newline?

### ISSUE THREAD

**Issue by alliquot** [davidgohel/ReporteRs#59]
Let's suppose that I have a very long caption of a table and want to split it placing "soft enter" in some places:

Table 1:  A very long ....... ...... ..... caption (some additional text comes here). More text.

This is what I want to achieve:
Table 1: A very long ...... caption
(some additional text comes here)
More text.

There is only one paragraph with autonumbering style applied, not two. Word allows splitting it by pressing "shift+enter". How can I do the same with addParagraph?

**Comment by davidgohel** [comment]
on github

You will get a *soft return* if using `\n`.

**Comment by alliquot** [comment]
Thank you very much!
This works perfectly!
