### ISSUE TITLE
ReporteRsjar doesn't work with R version 3.1.2

### ISSUE THREAD

**Issue by aghaynes** [davidgohel/ReporteRs#62]
More as a note than a question, the jar defining package refuses to install on the newest version of R (3.1.2). It works ok on R 3.1.1.

ReporteRsjars and ReporteRs give warnings that they were built under the R 3.1.2 though. Which seems to be confusing, although it seems to work, so I'm not overly concerned.

Cheers,

Alan

**Comment by davidgohel** [comment]
Hi Alan, 

It works for me...

Could you send me the result of `sessionInfo()` and also copy the exact message you are getting?

Thanks,
David

**Comment by aghaynes** [comment]
Hi David,

I just tried it again and it's worked fine...I don't think I did anything
differently though...

Why is it that you try things hundreds of times without it working and then
when you try to show someone it works fine...!? Maybe I was trying the
64bit version before...I dont know.

Thanks anyway!

Alan

> sessionInfo()R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252
[3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C
[5] LC_TIME=German_Switzerland.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] tools_3.1.2> install.packages("ReporteRs")Warning in install.packages :
  downloaded length 148112 != reported length 200
Warning in install.packages :
  downloaded length 227 != reported length 200also installing the
dependency ‘ReporteRsjars’
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/ReporteRsjars_0.0.2.zip'Content
type 'application/zip' length 5502827 bytes (5.2 Mb)opened
URLdownloaded 5.2 Mb
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/ReporteRs_0.7.2.zip'Content
type 'application/zip' length 897849 bytes (876 Kb)opened
URLdownloaded 876 Kb
package ‘ReporteRsjars’ successfully unpacked and MD5 sums checked
package ‘ReporteRs’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\i0309599\AppData\Local\Temp\RtmpwPthGz\downloaded_packages>
library(ReporteRs)Lade nötiges Paket: ReporteRsjars


--------------------------------------------------
Email: aghaynes@gmail.com
Mobile: +41763389128
Skype: aghaynes

**Comment by davidgohel** [comment]
You're welcome. 

Glad it is not a bug ;)
