### ISSUE TITLE
Greek Characters in Flextable

### ISSUE THREAD

**Issue by gilleschapron** [davidgohel/ReporteRs#63]
Hello David,

I wonder if there is a way to add special characters in a cell of FlexTable (like greek characters in my case).
I do not know if its possible with pot().
I have tried also to add a stringi package variable but with no success.

Thank you for any answer.

**Comment by davidgohel** [comment]
Hello Gilles

Yes. For example:

    xx = vanilla.table( iris[1:5, ] )
    xx[1,1, newpar=TRUE] = "ß"
    xx[2,2, newpar=TRUE] = pot( "a", textProperties( font.family = "Symbol" ) )
    xx

If any problem, you can read that discussion that may help: https://github.com/davidgohel/ReporteRs/issues/38

Hope it helps,
David

**Comment by gilleschapron** [comment]
Thank you for your quick answer.

The thing is, in my script that produce reports with tables and graphics, I would like to insert identical  combination of greek characters and normal (bold) text in tables and graphics.
So what's work with pot() + "symbol" in tables does not work properly in graphics titles (in fact works with vector.graphic = FALSE but not with TRUE)...
For graphics, you could answer me that I could use expression(), but "symbols" will not be bold !

All of that is not very important, but I think Unicode character integration would be very usefull thing, but seems to be tricky.

Gilles

**Comment by davidgohel** [comment]
Hi again,

With the following code, I get the same symbol in my graph and in my table (graph is a vector graphic one and ß is bold):

    doc = docx()
    
    pp = function(){
      plot(1:10, 50:41)
      text(5, 45, labels = "ß", font = 2)
      title( "ß", font = 2)
    }
    
    xx = vanilla.table( iris[1:5, ] )
    xx[1,1, newpar=TRUE] = "ß"
    
    
    doc = addPlot( doc, fun = pp, vector.graphic = T)
    doc = addFlexTable( doc, xx)
    
    writeDoc( doc, "toto.docx")


David

**Comment by gilleschapron** [comment]
Your right, I think it's probably because ß is part of Latin1-supplement block of Unicode.
If you try a Greek character, for exemple in my case gamma : 

```R
doc = docx()

pp = function(){
  plot(1:10, 50:41)
  text(5, 45, labels = "γ", font = 2)
  title( "γ", font = 2)
}

xx = vanilla.table( iris[1:5, ] )
xx[1,1, newpar=TRUE] = "γ"


doc = addPlot( doc, fun = pp, vector.graphic = T)
doc = addFlexTable( doc, xx)

writeDoc( doc, "toto.docx")
```
Does not work anymore (only for the table), never with code "\u03b3".
Note the strange thing : mu is working with "\u03bc", which is part a the Greek Unicode block (identical to "\u00b5" in Latin1-supplément block), but I think it's the only one....

Thanks for your time.

**Comment by gilleschapron** [comment]
Me again ^^
If I'm not wrong, generation of docx is made with docx4j v3.0.0 java package.
I'have seen in the changelog that there is some improvement support of Arial Unicode in version 3.2.
Usefull... or not.

**Comment by alliquot** [comment]
Is there any chance to get ReporteRs working with Unicode (UTF8)?

Currently it doesn't work. 
http://s30.postimg.org/8y6c26qb5/langs.jpg

R console cannot display it correctly, however, RStudio handles it correctly via "View"
http://s16.postimg.org/91khdwmkl/langs2.jpg

**Comment by davidgohel** [comment]
yes, 
it is on the todo list

**Comment by alliquot** [comment]
Hi David,

I thought you may find this information useful.

If you run this code:
df=data.frame(LANG=c("PL", "DE", "FR", "DU", "TUR"), Text=c("ąęóąśłżźćń", "äöüß", "ùàâûüæçÿ€éèêëïîôœ", "éëïóöü€", "çğıİöşü"))
doc = docx()
ft = FlexTable(df)
doc = addFlexTable(doc, ft)
writeDoc(doc, "test.docx")

Can you see all characters for the FRance row?
I cannot see some of them:
http://s21.postimg.org/rfgjpvrs7/lang_result.png

**Comment by davidgohel** [comment]
Hi

Please provide 

    sessionInfo()

This is a result from a mac. 
http://postimg.org/image/lgrkjrmd1/

What OS are you running?

David

**Comment by alliquot** [comment]
I tried many of fonts but with no success. As previously, some "accented" letters are not displayed, they are converted into plain ASCII letters.

My session:

> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

attached base packages:
[1] tcltk     stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ReporteRs_0.8.0      ReporteRsjars_0.0.2  stringr_0.6.2        XML_3.98-1.1         gWidgetstcltk_0.0-55 digest_0.6.8        
 [7] RODBC_1.3-11         knitr_1.9            gdata_2.13.3         gWidgets_0.0-54      rJava_0.9-6         

loaded via a namespace (and not attached):
 [1] bitops_1.0-6         colorspace_1.2-6     devtools_1.7.0       evaluate_0.5.5       formatR_1.1          ggplot2_1.0.1       
 [7] grid_3.1.3           gtable_0.1.2         gtools_3.4.2         gWidgets2_1.0-6      gWidgets2tcltk_1.0-5 httr_0.6.1          
[13] MASS_7.3-40          memoise_0.2.1        munsell_0.4.2        plyr_1.8.1           proto_0.3-10         Rcpp_0.11.5         
[19] RCurl_1.95-4.5       reshape2_1.4.1       scales_0.2.4         tools_3.1.3

**Comment by davidgohel** [comment]
Yes, things are different from Windows. And ReporteRs do not translate native encoding to utf8 yet.

If you have clear ideas on how to manage that from Word and PowerPoint and HTML on windows, please do share the code. Actually, I am working on UTF-8 capabilities for graph device during evenings and I don't have available time on this subject until the previous subject is solved.

**Comment by davidgohel** [comment]
@alliquot can you contribute or not?

**Comment by alliquot** [comment]
I'm afraid I cannot. I don't know Java and currently - have no time :( I really appreciate your brilliant work but what I can do now is only put here some clues or share my experiences.

**Comment by alliquot** [comment]
BTW: What if interesting - even using my Polish locale, I can display some Cyrillic characters:
> '\u0424'
[1] "Ф"
> '\u0425'
[1] "Х"
> '\u0426'
[1] "Ц"
> '\u0427'
[1] "Ч"
> '\u0428'
[1] "Ш"
> '\u0429'
[1] "Щ"

If there was a way of translating all characters into form \uXXXX (via "paste0()") and create from it the output...
eval(parse(text=paste0("'", "\\u0429", "'")))
[1] "Щ"

It works for French accented and other special characters (acute, grave, circumflex, umlaut/diaeresis):
> eval(parse(text=paste0("'", "\\u00e0", "'")))
[1] "à"
> eval(parse(text=paste0("'", "\\u00c7", "'")))
[1] "Ç"
> eval(parse(text=paste0("'", "\\u00cb", "'")))
[1] "Ë"
> eval(parse(text=paste0("'", "\\u00ce", "'")))
[1] "Î"

But not for all.
should be: Œ
> eval(parse(text=paste0("'", "\\u008c", "'")))
[1] "\u008c"

**Comment by drhagen** [comment]
I have this as a workaround in Windows at least when printing Unicode characters to Word documents:

```
# Set locale to C
Sys.setlocale("LC_CTYPE", "C")
# Insert UTF-8 characters bytewise
str <- '\xCF\x83'
# Mark the string as natively encoded
Encoding(str) <- 'native.enc'
```

This string can be sent to `FlexTable ` functions and the bytes appear to be written out verbatim, which are then interpreted as UTF-8 in the context of a Word document.
