### ISSUE TITLE
[Enhancement] addField(doc, "SEQ Figure \* roman") -- adding fields into a document

### ISSUE THREAD

**Issue by alliquot** [davidgohel/ReporteRs#65]
Dear David,

Would it be possible to add a function that adds a "field" in the current place in a document? I mean: http://officeopenxml.com/WPfieldDefinitions.php

You know, something like: addField(doc, "SEQ Figure \* roman"). This adds an XML "node" defining a field with a given content in the current place in the current document.

This would allow one to define more complex autonumeration definitions (where a section number is concatenated with number of an object etc.), manipulate the sequence, change its style. Using styles with an autonumeration option has a big disadvantage - if you put "soft break" after a "Table X." text it reveals an additional tabulation mark which Word adds automatically. And you cannot easily concatenate different information in it.

Moreover, it would be really nice if one could insert current date or author fields and so on. For instance when creating a title pages.

Since those fields are standardized and interchangeable with OpenDocument and even RTF, it would be a great enhancement!

**Comment by davidgohel** [comment]
Very good suggestion! Thanks

It will be part of an improvement of `pot` objects (they need to allow inline images also). 

David

**Comment by alliquot** [comment]
That's great, David! You make R a very competitor of SAS in creating documents (SAS utilizes RTF). You have already done something really BIG for the world of R :+1:

**Comment by alliquot** [comment]
Hello David!
I'm sorry for returning to this topic again, but do you have any plans regarding this enhancement?

**Comment by davidgohel** [comment]
Hello,

Unfortunately, I don't have enough time to work on that at the moment. You will have to wait few months (or propose  a pull request :)).

David

**Comment by alliquot** [comment]
Few months is still worth waiting :) since it enables lots of possibilities during the document creation :) Thank you!

**Comment by alliquot** [comment]
Hello after a year :)
Is there any chance to add the described functionality? Inserting custom field is really helpful when creating advanced reports that are to be merged and use custom paragraph numbering...

**Comment by davidgohel** [comment]
It's unlikely 

Values of custom fields seem to be updated by MS Word but ReporteRs do not use Word to generate documents, so it's out of scope of ReporteRs.
