### ISSUE TITLE
[Request] spanFlexTableRows on headers

### ISSUE THREAD

**Issue by gilleschapron** [davidgohel/ReporteRs#67]
Hello David,

When you have some time, could you please add the possibility to use function spanFlexTableRows on headers and footers ?
My apologies if its already possible.

Regards, and thanks again for your work,

Gilles

**Comment by davidgohel** [comment]
Hello Gilles,

Thanks,

Right, actually you can span columns in a row but you can not span rows in headers (neither in footers). I will solve that in a later version.

David

**Comment by gilleschapron** [comment]
Hello David,

Did you have some time to add this feature ?
I have not seen it in the News file since.

Regards,

Gilles

**Comment by davidgohel** [comment]
Hi Gilles

The `flextable` package (soon on cran) allows rows or columns span in header and body of the table (works only with officer for now). Implementation of flextable within ReporteRs is not planned but will happen in the next round of devel/debug.

David
