### ISSUE TITLE
Flextable in RStudio

### ISSUE THREAD

**Issue by glennmschultz** [davidgohel/ReporteRs#68]
Hi, I was trying to use Flextable in R Studio as part of .Rmd file and then using the option knit to Word. Flextable does not seem to work under this scheme.  Perhaps because a document needs to be specified.  Below is the markdown code that I am using in R Studio.  Maybe I am doing something wrong.  Nonetheless, really cool package.

Glenn

title: "Short Term Prepayment Projections"
output: word_document
---

February Projections

Below is a graph of our Feb. 2015 short-term predictions for FNMA 30-year MBS

```{r  fig.height=8 ,fig.width=7 ,echo = FALSE, message=FALSE}
library(ggplot2)
library(gridExtra)
library(ReporteRs)
library(rJava)
options( "ReporteRs-fontsize" = 3 )

FlexTable(predicted)

#grid.table(predicted[,c(2,3,5)])

PlotData <- data.frame(cbind(predicted$Coupon, 
                predicted$PoolOrigYear, 
                 predicted[,12], 
                (predicted[,12]/predicted[,11])-1))
                colnames(PlotData) = c("Coupon", "PoolOrigYear", "CPR","PctChg")

        plot1 <- ggplot(subset(PlotData, (PoolOrigYear >= 2003 & PoolOrigYear <=2006) & Coupon <= 5.5), 
            aes(x = as.factor(Coupon), y = CPR, weight = PctChg, colour = PctChg))+
                        geom_point(alpha = 0.8, guide = "none") +
                        facet_grid(.~PoolOrigYear) +
                         theme(axis.text.x=element_text(size = 7))

       
        plot2 <- ggplot(subset(PlotData, (PoolOrigYear >= 2007 & PoolOrigYear <=2010) & Coupon <= 5.5), 
            aes(x = as.factor(Coupon), y = CPR, weight = PctChg, colour = PctChg))+
                        geom_point(alpha = 0.8, guide = "none") +
                        facet_grid(.~PoolOrigYear) +
                         theme(axis.text.x=element_text(size = 7))

       plot3 <- ggplot(subset(PlotData, (PoolOrigYear >= 2011 & PoolOrigYear <=2014) & Coupon <= 5.5), 
            aes(x = as.factor(Coupon), y = CPR, weight = PctChg, colour = PctChg))+
                        geom_point(alpha = 0.8, guide = "none") +
                        facet_grid(.~PoolOrigYear) +
                         theme(axis.text.x=element_text(size = 7))

        grid.arrange(plot1, plot2, plot3, nrow = 3 )
   
```

**Comment by davidgohel** [comment]
Hi 

Sorry for the late answer. 

The only way to add a FlexTable into a Word document is to use `docx` object. 

    doc = docx()
    doc = addFlexTable( doc, your_flextable)
    writeDoc(doc, "your_flextable.docx")

You can use `FlexTable` within knitr but it will only work with HTML output. In the current version of ReporteRs:

    ```{r results='asis'}
    cat(as.html(your_flextable))
    ```

Note: there is a new package [rtable](https://github.com/davidgohel/rtable) where usage of `FlexTable` within knitr (html output) is easier:

    ```{r}
    your_flextable
    ```

**Comment by alliquot** [comment]
Thanks for sharing the rtable! Dear David, you are a god :+1:

**Comment by glennmschultz** [comment]
Thanks, for the feedback.  I will look into the rtable package.

**Comment by davidgohel** [comment]
@alliquot :)

**Comment by agstudy** [comment]
Hi , Is there any option to print FlexTable within an Rmd knitr file and knitted in pdf ?

**Comment by davidgohel** [comment]
Hi, 

No. Maybe one day I will find time to develop the latex output but it's not planned yet.

David

**Comment by agstudy** [comment]
Maybe I can help ( if I have enough time) and contribute to it. One can be inspired by 

     print.xtable(..,type='htm')  

This works well within `knitr` : 


```
{r chunkTest, echo=FALSE, results='asis'}
print(xtable(anova(fm3)), type = "html")
```

**Comment by davidgohel** [comment]
This is a feature of `rtable` package. You can have a look here: http://davidgohel.github.io/tabular/

`xtable` objects are translated into `FlexTable` and can be (modified if necessary) and then printed *as is* from knitr (it only works with HTML output)

David

**Comment by eusebe** [comment]
Hi, 
This is an old issue, but I think it may be usefull to include FlexTable objects to a Rmd file processed to docx format. FlexTable function is, to my point of view, the more powerfull tool to create complex tables. Knitr workflow is very intuitive. When producing a word document with knitr,  tables are limited to the (limited) pandoc/markdown features.

Perhaps this is not related to ReporteRs, and that there could be a way, with pandoc, to include some openxml or html code into the produced word document?

**Comment by davidgohel** [comment]
Hi

Yes, I'd like to also. I already investigated the question and I don't think it can be done in *seamless* mode.

The only workaround would be to add a bookmark and then with `ReporteRs` to replace paragraph where bookmark is by the FlexTable. To me, this really can't be done within knitr workflow (I may be wrong but it seems the bottleneck is pandoc that do not allow xml insertion).

**Comment by behrica** [comment]
I found an interesting way to have better support for complex tables in Word.
The basic idea is to include tables as images (png).

With something like phantomjs it is easy to convert any html to png, which can be included in the Rmarkdown file.

I have a working pipeline like this:

FlexTable -> as.html -> toPng (with phantomjs) -> knitr::include_graphics

This allows arbritary styling as any html can be used.

In this FlexTable is one possible way to get the html, a package like 'htmlTable' is an other way.

**Comment by behrica** [comment]
I found an other way to combine FlexTable and markdown into a word document.
It's just a hack for now, but it works.

In markdown, for each "data.frame" I want to include in my word document, I do two things:
  1. render it with knitr::kable(df) in the chunk, which inserts the table content as an (ugly / simple) table.
  2. I use FlexTable(df)  %>% addParagraph(pot("a unique caption text"))   %>% writeDoc(..)  to create a small word document containing only the single nice formated word table and a caption text.

Then after the docx is created with 'pandoc', I post-process the xml of the docx file and **replace inside the docx file** the xml chunk of the 'simple' table created by kable/pandoc with the xml chunk from the file generated by FlexTable.
I use a 'unique caption text' to know what xml node to replace by which xml node.

Compared to using an image (which might become 'blurr', eventhough I think this can be solved by using a high resolution screenshot (> 300 dpi)), this results in having a 'real' table in the word file.

**Comment by lmwang9527** [comment]
@behrica that sounds like a fantastic hack in the imperfect disconnected universe of pandoc/kable/ReporteRs! Would you mind sharing how you do "post-process the xml of the docx file" with the replacing etc? Thanks!

**Comment by behrica** [comment]
```R

##' Creates a docx file with the FlexTable objecta and a caption
##'
##' @param ft The FlexTable to add to the doxc file
##' @param docxFile Path of the docx file to create
##' @param caption The caption text to put above the table
##' @export
makeDocxWithFt <- function(ft,docxFile,caption) {
  docx=ReporteRs::docx() %>%
   ReporteRs::addParagraph(ReporteRs::pot(caption))  %>%
      ReporteRs::addFlexTable(ft) %>%
      ReporteRs::writeDoc(docxFile)

    }
##' Replaces table in a give docx file with corresponding FlexTable docx files.
##' They are matched by caption.
##'
##' @param inputDocxFile The base docx file to modify
##' @param flexTableDocxFiles List of FlexTable docx files as replacements
##' @param outputDocxFile The output docx file
##' @export
patchFlexTables <- function(inputDocxFile,flexTableDocxFiles,outputDocxFile) {

    tableNodes_new <- flexTableDocxFiles %>%
        purrr::map(function(docx) {
            captionNode=unz(docx,"word/document.xml") %>%
                readr::read_file() %>%
                xml2::read_xml() %>%
                xml2::xml_find_first("//w:t")

            captionText <- captionNode %>%
                xml2::xml_text()
            tableNode <- captionNode %>%
                xml2::xml_parent() %>%
                xml2::xml_parent() %>%
                xml2::xml_siblings() %>%
                magrittr::extract2(1)
                                        #as.character()

            list(captionText=captionText,tableNode=tableNode)
        })


    xml=unz(inputDocxFile,"word/document.xml") %>%
        readr::read_file() %>%
        xml2::read_xml()



    xml2::xml_find_all(xml,"//w:tbl") %>%
        purrr::walk(function(tableNode) {
            currCaptionText <- tableNode %>%
                xml2::xml_find_first(".//w:tblCaption") %>%
                xml2::xml_attr("val")
            if (is.na(currCaptionText))
                return()
            match <- purrr::detect(tableNodes_new,~ .x$captionText == sub(pattern = "^Table [[:digit:]]* ",
                                                                         replacement="",
                                                                         currCaptionText))



            captionNode=xml_new_root("xml",
                                     xmlns ="http://default",
                                     "xmlns:w"="http://schemas.openxmlformats.org/wordprocessingml/2006/main") %>%
              xml_add_child("w:tblCaption","w:val"=currCaptionText)



            match$tableNode %>%
              xml_find_first(".//w:tblPr") %>%
              xml_add_child(captionNode)

#browser()
            xml2::xml_replace(tableNode,.value=match$tableNode)
            print(tableNode)
        })
    enhancedDir = tempfile("dir")
    R.utils::mkdirs(enhancedDir)
    unzip(inputDocxFile,exdir=enhancedDir)
    xml2::write_xml(xml,paste0(enhancedDir,"/word/document.xml"))
    outputTempFile <- tempfile(fileext = ".docx")

    wd <- getwd()
    setwd(enhancedDir)
    tryCatch({
        zip(outputTempFile,list.files(".","*",full.names = T,recursive = T,all.files = T))
    },finally=setwd(wd))

    result <- file.copy(outputTempFile,outputDocxFile,overwrite = T)

}

#patchFlexTables("./_book/_main.docx",
 #               list.files("./output",pattern = ".docx",full.names = T),
  #              "./_book/_main_enhanced1.docx"
   #             )
```

**Comment by davidgohel** [comment]
This will be solved in flextable by @mnazarov 

https://github.com/davidgohel/flextable/issues/34

But this will not be compatible with ReporteRs...

**Comment by lmwang9527** [comment]
@behrica Thanks for sharing your code; I appreciate it!

@davidgohel thanks for pointing the open issue; I will certainly cast my vote for implementing the function.

**Comment by madhuripatil003** [comment]
Hi,

I am trying to add flextable ( I used conditional formatting on flextable using flextable package only) to Powerpoint using "officer" package. when I ran the code it's throwing no-error but when try to open the powerpoint it's showing "Powerpoint found a problem with the content in "test1.pptx" Powerpoint can attempt to repair the presentation". And gives 2 options 1.Repair 2.Cancel 
If I choose 1. Repair - It shows a blank table in ppt
                  2. Cancel- Its damages the file.
Here is my code-
`myPres <- PPTAddTitleOnlySlide(myPres,"CPK_data") 
TR_CPKdf=FlexTable(my.CPkdf1)%>%
  theme_booktabs()
cnames=colnames(my.CPkdf1[3:ncol(my.CPkdf1)])
png("flextable.png")
for (i in cnames) {
  TR_CPKdf[as.numeric( sub("%", "", my.CPkdf1[, i])) < 1, i] = cellProperties( background.color = "red" )
  TR_CPKdf[as.numeric( sub("%", "", my.CPkdf1[, i])) >= 1 & sub("%", "", my.CPkdf1[, i])< 1.32 , i] = cellProperties( background.color = "yellow" )
  TR_CPKdf[ as.numeric( sub("%", "", my.CPkdf1[, i])) >= 1.32, i] = cellProperties( background.color = "green" )
}   

myPres=ph_with_flextable_at(myPres,TR_CPKdf, left = 4, top = 4)
print(myPres,"test1.pptx")`

Within R it's properly showing the desired output.A conditional formatting table in "Viewer Pane" with no error.

Can please help me this. What is that I am doing wrong?

Regards
Madhuri.
