### ISSUE TITLE
help function don't work

### ISSUE THREAD

**Issue by htc502** [davidgohel/ReporteRs#69]
when I type in help(package="ReproteRs") on win7 R3.1.0 X64 version,
it says that "No package named ReproteRs could be found". seems that the help function dosen't work.
by the way, this package is great ~_~

**Comment by davidgohel** [comment]
Hi, you've made a typo

    help(package="ReporteRs")

**Comment by htc502** [comment]
wow, got it done. sorry for my absent-minded question..
