### ISSUE TITLE
FlexTable text angles

### ISSUE THREAD

**Issue by claire-oi** [davidgohel/ReporteRs#70]
Is it possible to have header row text at a 45 degree angle or vertical (instead of horizontal)? I do not see angle as a text property.

Thank you, this package is great.

**Comment by davidgohel** [comment]
Hi,

This is a parameter that should go in the cellProperties function. I will tell you when this will be available. 

I don't think we can do 45% with Word tables nor PowerPoint so available options might just be : 'horizontal', 'rotate 90', 'rotate 270'.
 
David

**Comment by claire-oi** [comment]
Hi David,

Thank you so very much -  this is amazing, and your package is brilliant.


Claire

**Comment by davidgohel** [comment]
Hi,

You can get the new release ReporteRs-0.7.9 [here](http://github.com/davidgohel/ReporteRs/releases/tag/v0.7.9).

I wrote a small post to explain how it works:
http://davidgohel.github.io/r/flextable/flextable-rotate-text/

This was a important missing feature...

David

**Comment by davidgohel** [comment]
You're welcome
