### ISSUE TITLE
addFlexTable doesn't honor par.properties when replacing a bookmark

### ISSUE THREAD

**Issue by alliquot** [davidgohel/ReporteRs#73]
I defined a bookmark and tried to replace it with a FlexTable. It worked with one exception - not all paragraph properties were honored. Only text.align worked, but padding - didn't.

doc = addFlexTable(doc, ft, bookmark = "myBookmark", par.properties = parProperties(text.align="center", padding.top = 130, padding.bottom = 50))

Neither pading.top nor padding.bottom were applied.

Is this behavior intended? Is there any workaround to make some space between my bookmarked paragraph and a table?

Hmmm, it seems that the only way to handle this issue is to define a paragraph containing a single space, set a bookmark on it and then put a table below...

**Comment by davidgohel** [comment]
I don't think we can apply padding to a table in a Word document. 
Are you able to do it within Word?

Workaround would be to add padding to preceding paragraph or following paragraph
