### ISSUE TITLE
windows binary installation

### ISSUE THREAD

**Issue by jdbricker** [davidgohel/ReporteRs#75]
I didn't see this mentioned anywhere, but to install the windows binaries from my local drive I had to do:
install.packages("C:/work/ReporteRsjars_0.0.2.zip", repos = NULL,type="win.binary")
and:
install.packages("C:/work/ReporteRs_0.7.9.zip", repos = NULL,type="win.binary")

**Comment by davidgohel** [comment]
OK
Thanks for the comment

**Comment by davidgohel** [comment]
The readme has been updated.

David
