### ISSUE TITLE
A problem with tables under Open(Libre) Office.

### ISSUE THREAD

**Issue by alliquot** [davidgohel/ReporteRs#77]
Hello David,

Today I've faced a strange issue. Some time ago we discussed a problem with Unicode under Windows. Since I had to manage this, I decided to generate a document under Linux to check whether it solves the problem. And it did. But under Linux I'm using Open Office and when I opened the newly generated document I noticed, that there is no table but rather a paragraph of text.

I copied the document into Windows and opened it in Word, Libre Office and Open Office (newest versions). Below is what I have seen:
![reporters_table1](https://cloud.githubusercontent.com/assets/9018389/7556205/b594901c-f767-11e4-968a-ce7ed0c6f84c.png)

I was really surprised why both OO/LO don't recognize a simple table. I added another one below (the blue one) and saved the document. I reopened it in OO and LO and... It worked.
![reporters2](https://cloud.githubusercontent.com/assets/9018389/7556204/b590fcf4-f767-11e4-91ce-9ab7077a6c35.png)

So thought I will try to add an empty paragraph in R code after the first table - perhaps it will help. Nope, it didn't work. So I added another FlexTable after. With no success.

It seems that adding the new table manually in Word fixed the document but doing the same in R code (adding paragraph, adding FlexTable) - didn't.

Do you have any idea what could happen? Is this a problem with OpenOffice or ReporteRs?

I'm using the newest ReporterRs, built from sources. It behaves the same under Windows and Linux.

**Comment by davidgohel** [comment]
Hello,

I don't know LO enough to explain your issue. Unfortunately there is no plan to ensure compatibility with LO software.

David

**Comment by alliquot** [comment]
Hello David,

OK, I understand.

Just a note for those who want to quickly fix the file: In any place of the document, type any character (or just hit Enter, space) and then remove it (or even live it, if you want).

*Any kind* of edition fixes the file so OO/LO displays it correctly.

**Comment by davidgohel** [comment]
OK, I will keep that in mind in the future - it may help to find out what is going on with LO. 

Thanks
