### ISSUE TITLE
spanFlexTableRows() runs argument with as.FlexTable(ftable) from rtable package

### ISSUE THREAD

**Issue by dickli** [davidgohel/ReporteRs#78]
Hi David,

I'm using both your terrific packages to transform an ftable into a FlexTable. However, I'm having trouble merging cells after the FlexTable is created. The reason is because the number of rows of the flexed ftable is fewer than my original data frame and thus the runs argument from spanFlexTableRows() will not function. 

I've tried to access the vector directly from the created FlexTable, but it looks like that information is stored as a java object with several other data points. 

Do you have any suggestions about how to merge those cells from a flexed ftable? Many thanks!

Best,
Richard

**Comment by davidgohel** [comment]
Hi 

Are you trying to merge header cells and *row names* cells? Or the body content?
You can easily merge *row names*:

    library( rtable )
    mtcars_ftable = ftable(mtcars$cyl, mtcars$vs, mtcars$am, mtcars$gear, 
       row.vars = c(2, 4),
       dnn = c("Cylinders", "V/S", "Transmission", "Gears"))
    
    row.vars = attr( mtcars_ftable, "row.vars" )
    rows = rev( expand.grid( rev( row.vars ) ) )
    rows = as.matrix( rows )
    
    FT = as.FlexTable( x = mtcars_ftable ) 
    FT = spanFlexTableRows(FT, j = 1, runs = rows[,1])
    print( FT )

**Comment by dickli** [comment]
Ahh you grabbed the vector directly from the ftable. That makes a lot more sense than trying to grab it from the FlexTable. Many thanks!
