### ISSUE TITLE
How to set row heights in FlexTable?

### ISSUE THREAD

**Issue by drizztxx** [davidgohel/ReporteRs#79]
Hi David,

Thanks for your fantastic work!

With setFlexTableWidths() we can easily set the widths of specified columns. While when I want to change the heights of one row (e.g. change to 1.5 line spacing of the header), how can I do it?

Best Regards,

Drizzt

**Comment by davidgohel** [comment]
Hi 

You can use the 'padding argument' of parProperties or cellProperties.

But there is no *setTableRowHeight* function to let you specify the height. I am using padding a lot as most often I just want to have headers with more space around my text...

David
