### ISSUE TITLE
Center title of pp presentation

### ISSUE THREAD

**Issue by agstudy** [davidgohel/ReporteRs#80]
I am creating a slide like this 

        mydoc = addSlide( mydoc, "Title and Content" )
        mydoc = addTitle( mydoc, "This is a title" )

The title is at the left of the box , How can I center it? Is there any option to format text position?

**Comment by agstudy** [comment]
I think that using template can be an option.
[here more detailed answer](http://stackoverflow.com/questions/31039115/center-title-of-as-slide-of-power-point-presentation) in SO.

**Comment by davidgohel** [comment]
It looks you solved your issue. I am closing the ticket, reopen it if necessary.

David

**Comment by agstudy** [comment]
Thank you a lot for this work. +5 stars!
