### ISSUE TITLE
addPlot fails when I import ReportRS in a new package

### ISSUE THREAD

**Issue by agstudy** [davidgohel/ReporteRs#81]
I am trying to integrate `ReporteRS` within another R package.  
When I import set the ReportRs dependency as an **Imports** the `addPlot` fails silently ( I think due to try catch in your call to the plot function passed as parameter). The message is something like this:

           could not find function "FontMetric"

When I set ReportsRs as a **Depends** it works fine.

**Comment by davidgohel** [comment]
Hi,

And what if you use
 
    importFrom(ReporteRs, FontMetric)

in your namespace file?

**Comment by agstudy** [comment]
I don't know but I can't reproduce the error.

The `ReporteRS` works fine now as an `imports`. I don't know what happens but probably the error is due to some old packages ( UI updates all my dependencies)

Thank's again for you help.

**Comment by davidgohel** [comment]
OK, perfect

++
