### ISSUE TITLE
Workflow for custom (non-placeholder) slides?

### ISSUE THREAD

**Issue by jpmorris** [davidgohel/ReporteRs#83]
Thanks so much for your work on this David.

I am confused about how to add custom slides to my presentation (and maybe there should be a slight clarification in the documentation).  And when I say 'custom' I mean nothing that requires placeholders per se.  Say I want to create a custom slide that uses animations, or audio files, or in my case different shapes (circles, arrows, etc).   Which is the proper workflow:

1) Create a SLIDE in the template file (but not as a layout) that has everything  exactly the way you want it  with audio/animation/shapes etc.
2) Create a LAYOUT in the template file that has everything exactly the way you want it with audio/animation/shapes etc.

If there is no dynamic content that needs to be added from ReporteRs, and many custom slides (animations, differnt flow diagrams, audio, that don't fit any layout etc) which is recommended 1 or 2?  The pros for 1 is that your LAYOUTS don't get bigger and bigger for all these custom slides, but you can't order the slides correctly.  The pros for 2 is that you can create the correct ordering by just doing an addSlide but you have to create lots of new layouts.  

I'm thinking that 2 is the way I want to go (assuming layouts support everything a normal slide does).

**Comment by davidgohel** [comment]
Hi

Yes, you can use the scenario 2.

You can also use addSlide with argument `bookmark` (a slide index) and replace the whole content of this slide with ReporteRs.
