### ISSUE TITLE
Bug in addTOC with stylenames (again)

### ISSUE THREAD

**Issue by olivierbarriere** [davidgohel/ReporteRs#85]
Hi again,

Thanks to your help, I managed to get the example working, but I am still not able to make it work with my own template. With the ReporteRs built-in template, it does work for some styles (including "rPlotLegend", "rTableLegend", "Titre",...), but not for other ones ("Lgende", "Titre1",...). What is needed for the Word style to have it listed by the TOC?

Here is a minimal example of the issue (the first example always works as expected, but not the second one):

doc = docx()
doc = toc.options( doc, list.separator = "," )
stylename="rPlotLegend" #"Titre","BulletList","rTableLegend"
doc = addParagraph( doc, value="TOC with stylename")
doc = addTOC(doc, stylename = stylename)
doc = addParagraph( doc, value="TOC without stylename")
doc = addTOC(doc)
doc = addParagraph( doc, value="graph example 1", stylename = stylename )
doc = addParagraph( doc, value="graph example 2", stylename = stylename )
doc = addTitle( doc, value="graph example 3")
doc = addTitle( doc, value="graph example 4")
writeDoc( doc, "addTOC_example1.docx" )

doc = docx()
doc = toc.options( doc, list.separator = "," )
stylename="Lgende" #"Titre1"
doc = addParagraph( doc, value="TOC with stylename")
doc = addTOC(doc, stylename = stylename)
doc = addParagraph( doc, value="TOC without stylename")
doc = addTOC(doc)
doc = addParagraph( doc, value="graph example 1", stylename = stylename )
doc = addParagraph( doc, value="graph example 2", stylename = stylename )
doc = addTitle( doc, value="graph example 3")
doc = addTitle( doc, value="graph example 4")
writeDoc( doc, "addTOC_example2.docx" )

**Comment by davidgohel** [comment]
Hi

`Lgende`is not valid as Word is truncating words with accents.

Send me your template, I will have a look.

**Comment by olivierbarriere** [comment]
I think I found the issue. The name of the style (in Word) needs to be without space (and also maybe without any special character). For instance, it will work with "Citation" but not "Citationintense".

I just renamed my own style from "Figure Title" to "FigureTitle" and it works as expected!
