### ISSUE TITLE
RStudio hangs on addPlot(fun = print, x = NULL)

### ISSUE THREAD

**Issue by ckluss** [davidgohel/ReporteRs#88]
Hi

thanks for the great package!

it's not really a bug, but maybe you can throw an error message instead 

doc <- pptx() %>% 
  addSlide("Title and Content") %>%
  addPlot(fun = print, x = NULL)

perhaps it has nothing to do with ReporteRs

Christof

**Comment by davidgohel** [comment]
Agree
A warning or maybe a stop to tell user something went wrong...

**Comment by davidgohel** [comment]
Now it prints:

    NULL
    Error in ls(envir = envir, all.names = private) : 
      argument 'envir' incorrect
