### ISSUE TITLE
addSlide, landscape DIN A4

### ISSUE THREAD

**Issue by ckluss** [davidgohel/ReporteRs#89]
Hi

is it possible to get a predefined DIN A4 landscape slide with 

addSlide(...) ?

Without to make a template. I do not realy get it in the documentation.

Best wishes
Christof

**Comment by davidgohel** [comment]
Hi,

No, it requires a template.

David

**Comment by davidgohel** [comment]
Hi

Tom Wenseleers made a nice package to export only graph and I think it answers your need:

https://github.com/tomwenseleers/export

David
