### ISSUE TITLE
Cannot print NA's to vanilla.table() after upgrading to rJava 0.9-7

### ISSUE THREAD

**Issue by vadimus202** [davidgohel/ReporteRs#90]
After upgrading to rJava 0.9-7, I get the following error when converting data frames with NA's in them. Downgrading to 0.9-6 fixes the problem

>vanilla.table(data.frame(x=1, y=NA))
**Error in .jcall(doc$jobj, "I", "writeHtml", file) : 
  java.lang.NullPointerException**

**Comment by davidgohel** [comment]
OK

Thanks for reporting that issue.

David

**Comment by davidgohel** [comment]
Should be solved now.

**Comment by vadimus202** [comment]
Thank you, David, for this terrific package! Great work!

**Comment by davidgohel** [comment]
Thanks :)
