### ISSUE TITLE
addPlot crashes when plot function calls strwidth

### ISSUE THREAD

**Issue by wurzerj** [davidgohel/ReporteRs#91]
Hi David,

First of all many thanks for your great work! I noticed that addPlot crashes when a plot function calls  strwidth.

Example Code (R 3.1.1, ReporteRs 0.8.2):
```
funTest <- function(...) {
	matplot(rnorm(10), pch=19)
	nWidth <- strwidth("test",units="user")
	invisible()
}
addPlot(doc, fun=funTest)
```

Result:
```
java.lang.ArrayIndexOutOfBoundsException: 2147483647Error in vector.pptx.graphic(doc = doc, fun = fun, pointsize = pointsize,  : 
  an error occured when executing plot function.
```

Regards,

Jürgen

**Comment by davidgohel** [comment]
Hi

Thanks for reporting that bug. I can reproduce it.
I don't know yet what is happening.

KR,
David

**Comment by rkabacoff** [comment]
I am still getting this error. Any idea what is going on?

**Comment by davidgohel** [comment]
There will be a fix soon (max next month).

David

**Comment by rkabacoff** [comment]
Thanks!!

Rob

Robert I. Kabacoff, Ph.D. | Vice President of Research
rob.kabacoff@mrg.com<mailto:rob.kabacoff@mrg.com> | p. 207.482.7303

[cid:image001.png@01CD7A24.0941C910]<http://www.mrg.com/>

[cid:image002.jpg@01CD7A24.0941C910]<http://www.linkedin.com/company/management-research-group>

**Comment by svenski** [comment]
+1 - looking forward to the fix!

**Comment by ChrisRackauckas** [comment]
Hey, I ran into a very similar problem. When I add a legend to a plot, it gives me this same error. The addPlot is simply

mydoc = addPlot(mydoc,fun = function() {plot(fitData$x,fitData$RA,xlab="x",ylab="RA",main="Fits, Pooled",cex.lab=labSize,cex.main=mainSize,cex.axis=axisSize)
                lines(xValues,RA.exp.predicted,col="red",lwd=plotLineWidths)
                lines(xValues,RA.lin.predicted,col="blue",lwd=plotLineWidths)
                lines(xValues,RA.quad.predicted,col="darkgreen",lwd=plotLineWidths)
                lines(xValues,RA.quad2.predicted,col="darkorange",lwd=plotLineWidths)
                legend('topleft',legendTxt,lty = c(1,1,1,1),lwd = legendlineWidths,col=plotCols,cex=legendTextSize)},vector.graphic=TRUE)

and without the legend, it's fine, but when I put the legend line back in there, it once again gives the Array out of bounds exception.

**Comment by davidgohel** [comment]
This should be solved with the new version.

David
