### ISSUE TITLE
Table breaking

### ISSUE THREAD

**Issue by aghaynes** [davidgohel/ReporteRs#93]
Hi,

Is it possible to stop tables breaking across pages if they are too long to fit on the remainder of the page? 

Thanks

Alan

**Comment by davidgohel** [comment]
Hi

I am not sure to understand the need. I understand you're are working with Word documents. 
What is your need, to hide or delete the rows that do not fit the page?

David

**Comment by aghaynes** [comment]
Hi David,

Yes, exactly, I'm working with Word documents.

Sometimes if there is a relatively short table, say 5 rows, and it happens
to occur at a place in the document thats almost at the end of the page, it
will break the table in 2 pieces with 2 rows on one page and the remaining
3 on the next page. I'd rather have all 5 rows on the next page... From an
aesthetic standpoint I believe that this makes sense...(it doesnt look
particularly nice having 2 very short tables when they would fit on a
single page without any issue).

Is that clearer?

Thanks,

Alan

**Comment by davidgohel** [comment]
OK, thanks for the clarification

You could add before your table

    addPageBreak(doc)

**Comment by aghaynes** [comment]
I actually have a lot of tables running in a big loop. If I used this then
the document would be enormous.

Is there some way to query the amount of space left on the page? Then I
could add a page break only if theres not enough space...

Thanks

Alan


--------------------------------------------------
Email: aghaynes@gmail.com
Mobile: +41763389128
Skype: aghaynes

**Comment by davidgohel** [comment]
No, I am afraid it's not possible.
