### ISSUE TITLE
Use customized template

### ISSUE THREAD

**Issue by wangyuchen** [davidgohel/ReporteRs#98]
Hi, I'm a little confused about the customized template in ppt output. The documentation said we should supply a ```.pptx``` file as template, but I noticed neither *theme* nor *template* in PowerPoint will be saved as ```.pptx``` file. After I pass a saved ```.pptx``` with my template to ```pptx()```, the document object can see all the layouts I have. However, when trying to open it, PowerPoint (2007) will give a warning, and the output ```.pptx``` file doesn't have the correct template and layout.

I'm wondering if you can provide some guidance on how to correctly supply a template. Thanks!

**Comment by davidgohel** [comment]
Hi

You posted the same message on google-groups and here, I will answer on gg.

David
